"""
Django settings for okletsdoit project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/planning/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/planning/
"""

from pathlib import Path
import socket

import environ
from csp.constants import NONE
from csp.constants import SELF
from csp.constants import NONCE

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    TIME_ZONE=(str, "UTC"),
    ALLOWED_HOSTS=(list, []),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    DJANGO_ACCOUNT_ALLOW_REGISTRATION=(bool, True),
    DJANGO_ACCOUNT_ALLOW_SOCIAL_REGISTRATION=(bool, True),
    AWS_S3_STATIC_DOMAIN_CSP=(str, ""),
    LOCAL_DEV=(bool, False),
    LOCAL_DB=(bool, True),
    AWS_SESSION_TOKEN=(str, None),
    AWS_ACCESS_KEY_ID=(str, ""),
    AWS_SECRET_ACCESS_KEY=(str, ""),
    AWS_REGION=(str, "us-east-1"),
    ALLOWED_CIDR_NETS=(list, []),
    NGINX_SERVER_NAME=(str, "dev.internal"),
    DJANGO_CORS_ALLOWED_ORIGINS=(list, ["http://localhost:5173", "http://localhost:4173", "dev.internal"]),
    EMAIL_BACKEND=(str, "django.core.mail.backends.smtp.EmailBackend"),
    EMAIL_HOST=(str, "smtp.gmail.com"),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_PORT=(int, 587),
)
env.read_env(BASE_DIR / ".env", overwrite=True)

SECRET_KEY = env("SECRET_KEY")
SERVICE_TOKEN = env("SERVICE_TOKEN")
DEBUG = env("DEBUG")
LOCAL_DEV = env("LOCAL_DEV")
LOCAL_DB = env("LOCAL_DB")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
ALLOWED_CIDR_NETS = env.list("ALLOWED_CIDR_NETS")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_extensions",
    "constance",
    "django_celery_beat",
    "django_celery_results",
    "health_check",
    "health_check.db",
    "health_check.storage",
    "health_check.contrib.migrations",
    "health_check.cache",
    "health_check.contrib.celery",
    "health_check.contrib.celery_ping",
    "health_check.contrib.redis",
    "widget_tweaks",
    "slippers",
    "allauth_ui",
    "allauth",
    "allauth.account",
    "allauth.headless",
    # "allauth.mfa",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.openid_connect",
    "import_export",  # https://django-import-export.readthedocs.io/en/latest/
    "simple_history",  # https://django-simple-history.readthedocs.io/en/latest/quick_start.html#install
    "csp",
    "django_cotton",  # https://django-cotton.com/docs/quickstart
    "crispy_forms",  # https://django-crispy-forms.readthedocs.io/en/latest/
    "crispy_formset_modal",  # https://blasferna.github.io/django-crispy-formset-modal/installation/
    "extra_views",  # https://django-extra-views.readthedocs.io/en/latest/pages/getting-started.html#installation
    # "pwa",  # https://django-pwa.readthedocs.io/en/latest/installation.html
    "ninja",
    "core",
    "attachments",
    "users",
    "expenses",
    "contacts",
    "list",
    "deadline",
    "guestlist",
]

if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",  # https://django-debug-toolbar.readthedocs.io/en/latest/
    ]

MIDDLEWARE = [
    "core.middleware.ServiceTokenSecurityMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "allow_cidr.middleware.AllowCIDRMiddleware",
]
if DEBUG:
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]


ROOT_URLCONF = "okletsdoit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "okletsdoit.context_processors.site_vars",
            ],
        },
    },
]

WSGI_APPLICATION = "okletsdoit.wsgi.application"

if LOCAL_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("POSTGRES_DB"),
            "USER": env("POSTGRES_USER"),
            "PASSWORD": env("POSTGRES_PASSWORD"),
            "HOST": env("POSTGRES_HOST"),
            "PORT": env("POSTGRES_PORT"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django_iam_dbauth.aws.postgresql",
            "NAME": env("RDS_DB_NAME"),
            "USER": env("RDS_USERNAME"),
            "HOST": env("RDS_HOSTNAME"),
            "PORT": env("RDS_PORT"),
            "OPTIONS": {
                "use_iam_auth": True,
                "sslmode": "require",
                "resolve_cname_enabled": True,
                "region_name": env("AWS_REGION"),
            },
        }
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL"),
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL"),
            "propagate": False,
        },
    },
}

REDIS_URL = env("REDIS_URL")
CONSTANCE_REDIS_CONNECTION = f"{REDIS_URL}/3"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
AUTH_USER_MODEL = "users.User"
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "account_login"

# django-allauth
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_ALLOW_REGISTRATION = env("DJANGO_ACCOUNT_ALLOW_REGISTRATION")
ACCOUNT_ALLOW_SOCIAL_REGISTRATION = env("DJANGO_ACCOUNT_ALLOW_SOCIAL_REGISTRATION")
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_FORMS = {"signup": "users.forms.UserSignupForm"}
ACCOUNT_ADAPTER = "users.adapters.AccountAdapter"
SOCIALACCOUNT_ONLY = False
SOCIALACCOUNT_ADAPTER = "users.adapters.SocialAccountAdapter"
SOCIALACCOUNT_FORMS = {"signup": "users.forms.UserSocialSignupForm"}
SOCIAL_PROVIDERS = "allauth.socialaccount.providers.openid_connect"
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": env.str("AUTHENTIK_CLIENT_ID"),
                "secret": env.str("AUTHENTIK_CLIENT_SECRET"),
                "settings": {
                    "server_url": env.str("AUTHENTIK_URL"),
                },
            },
        ],
    },
}

# django-allauth headless
HEADLESS_ONLY = False
HEADLESS_SERVE_SPECIFICATION = True
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"https://{env('NGINX_SERVER_NAME')}/auth/verify-email/" + "{key}",
}

# ADMIN
ADMIN_URL = "admin/"

LANGUAGE_CODE = "en-us"
TIME_ZONE = env("TIMEZONE")
USE_I18N = False
USE_TZ = True
APPEND_SLASH = False
PREPEND_WWW = False


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# HTTPS redirect
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Disable SSL redirect for service token requests (internal container communication)
# The ServiceTokenSecurityMiddleware will mark internal requests
SECURE_SSL_REDIRECT = True
SECURE_REDIRECT_EXEMPT = [
    r"^api/",  # Exempt API endpoints from SSL redirect
    r"^_allauth/",  # Exempt allauth endpoints for internal container auth checks
]
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS")


style_src = [
    SELF,
    "cdnjs.cloudflare.com",
    "cdn.ckeditor.com",
    "fonts.googleapis.com",
    "cdn.datatables.net",
    "cdn.jsdelivr.net",
    "'unsafe-inline'",  # Required for daisyUI 5 theme switching
]
if env("AWS_S3_STATIC_DOMAIN_CSP") != "":
    style_src.append(str(env("AWS_S3_STATIC_DOMAIN_CSP")))

CONTENT_SECURITY_POLICY = {
    "EXCLUDE_URL_PREFIXES": ["/excluded-path/"],
    "DIRECTIVES": {
        "default-src": [SELF],
        "script-src": [SELF, NONCE, "code.jquery.com", "cdn.jsdelivr.net"],
        "style-src": style_src,
        "font-src": [
            SELF,
            "data:",
            "cdnjs.cloudflare.com",
            "fonts.gstatic.com",
        ],
        "img-src": [SELF, "data:", "https:"],
        "connect-src": [SELF, "https://proxy-event.ckeditor.com"],
        "frame-src": [NONE],
        "object-src": [NONE],
        "base-uri": [SELF],
        "frame-ancestors": [SELF],
        "form-action": [SELF, "https://dev.internal", "https://auth.ianday.me"],
        # "report-uri": "/csp-report/",
        "upgrade-insecure-requests": True,
        "include-nonce": True,
    },
}

if env("AWS_S3_STATIC_DOMAIN_CSP") != "":
    CONTENT_SECURITY_POLICY["DIRECTIVES"]["script-src"].append(str(env("AWS_S3_STATIC_DOMAIN_CSP")))


# CORS Settings
CORS_ALLOWED_ORIGINS = env("DJANGO_CORS_ALLOWED_ORIGINS")
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_PREFLIGHT_MAX_AGE = 86400
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"

# django debug toolbar
INTERNAL_IPS = ["127.0.0.1", "10.0.2.2", "host.docker.internal", "localhost", "dev.internal"]
hostname, _, ips = socket.gethostbyname_ex(socket.gethostbyname(""))
INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: env.bool("DJANGO_DEBUG", False),  # type: ignore[arg-type]
    "DISABLE_PANELS": [
        "debug_toolbar.panels.redirects.RedirectsPanel",
        # Disable profiling panel due to an issue with Python 3.12:
        # https://github.com/jazzband/django-debug-toolbar/issues/1875
        "debug_toolbar.panels.profiling.ProfilingPanel",
    ],
    "SHOW_TEMPLATE_CONTEXT": True,
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": env("AWS_MEDIA_BUCKET_NAME"),
            "region_name": env("AWS_S3_REGION_NAME"),
            "access_key": env("AWS_ACCESS_KEY_ID"),
            "secret_key": env("AWS_SECRET_ACCESS_KEY"),
            "security_token": None,
            "endpoint_url": env("AWS_S3_ENDPOINT_URL"),
            "location": "media",
            "file_overwrite": False,
            "querystring_auth": True,
            "querystring_expire": 3600,
            "addressing_style": "path",
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": env("AWS_STATIC_BUCKET_NAME"),
            "region_name": env("AWS_S3_REGION_NAME"),
            "access_key": env("AWS_ACCESS_KEY_ID"),
            "secret_key": env("AWS_SECRET_ACCESS_KEY"),
            "security_token": None,
            "endpoint_url": env("AWS_S3_ENDPOINT_URL"),
            "location": "static",
            "file_overwrite": False,
            "querystring_auth": False,
            "custom_domain": env("AWS_S3_STATIC_DOMAIN"),
        },
    },
}
STATIC_URL = f"https://{env('AWS_S3_STATIC_DOMAIN')}/"
MEDIA_URL = f"https://{env('AWS_S3_MEDIA_DOMAIN')}/"

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
CELERY_RESULT_BACKEND_MAX_RETRIES = 10
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_TIME_LIMIT = 5 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 60
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# email
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("EMAIL_HOST_USER")  # Use the same email as the host user
EMAIL_URL_BASE = env("EMAIL_URL_BASE")
