# Generated by Django 5.2.4 on 2025-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicaltimeline_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltimeline',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
