# Generated by Django 5.2.4 on 2025-07-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_name_6f3a2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_created_71b3b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_is_dele_c46f23_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, help_text="Contact's website URL", null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_contact'),
        ),
    ]
