# Generated by Django 5.2.4 on 2025-09-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_file_is_deleted_file_updated_at_file_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='HistoricalFile',
        ),
    ]
