# Generated by Django 5.2.4 on 2025-07-13 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('item', 'category'), name='unique_expense_item_category'),
        ),
    ]
