# Generated by Django 5.2.4 on 2025-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='url',
            field=models.URLField(blank=True, help_text='URL for this item, e.g., a link to an online store or product page', max_length=1000, null=True),
        ),
    ]
