# Generated by Django 5.2.4 on 2025-07-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['due_date', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicaldeadline',
            name='priority',
        ),
    ]
