ARG BUN_IMAGE=oven/bun:1.4.0-slim

FROM ${BUN_IMAGE} AS builder
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3 \
    libblkid1=2.41.5-0+deb13u1 \ 
    bsdutils=1:2.41.5-0+deb13u1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install
COPY frontend/ ./
RUN bun run build

FROM ${BUN_IMAGE} AS development
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install
COPY frontend/ ./

EXPOSE 5173
CMD ["sh", "-c", "bunx svelte-kit sync && bun run dev"] 

FROM ${BUN_IMAGE} AS production
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3 \
    libblkid1=2.41.5-0+deb13u1 \ 
    bsdutils=1:2.41.5-0+deb13u1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/build ./build
CMD ["bun", "run", "build/index.js"] 