FROM oven/bun:canary-slim AS builder
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3t64 \
    libc-bin=2.41-12+deb13u2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install
COPY frontend/ ./
RUN bun run build

FROM oven/bun:canary-slim AS development
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3t64 \
    libc-bin=2.41-12+deb13u2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install
COPY frontend/ ./

EXPOSE 5173
CMD ["sh", "-c", "bunx svelte-kit sync && bun run dev"] 

FROM oven/bun:canary-slim AS production
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openssl \
    libssl3t64 \
    libc-bin=2.41-12+deb13u2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/build ./build
CMD ["bun", "run", "build/index.js"] 