FROM oven/bun:1 AS builder
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install
COPY . .
RUN bun run build

FROM oven/bun:1 AS development
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install
COPY frontend/ ./

EXPOSE 5173
CMD ["sh", "-c", "bunx svelte-kit sync && bun run dev"] 

FROM oven/bun:1 AS production
WORKDIR /app
COPY --from=builder /app/build ./build
CMD ["bun", "run", "build/index.js"] 