# Generated by Django 5.2.4 on 2025-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0003_guest_overnight_historicalguest_overnight'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='responded',
            field=models.BooleanField(default=False, help_text='Indicates if this guest has responded to the invitation'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='responded',
            field=models.BooleanField(default=False, help_text='Indicates if this guest has responded to the invitation'),
        ),
    ]
