# Generated by Django 5.2.4 on 2025-11-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0010_historicalrsvpsubmission_rsvpsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='guest',
        ),
    ]
