# Generated by Django 5.2.4 on 2025-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0014_remove_guest_response_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='accept_accommodation',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='accept_vip',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='accept_accommodation',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='accept_vip',
        ),
        migrations.AddField(
            model_name='guest',
            name='accept_accommodation',
            field=models.BooleanField(default=False, help_text='Indicates if this guest accepts accommodation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='accept_vip',
            field=models.BooleanField(default=False, help_text='Indicates if this guest accepts VIP status'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='accept_accommodation',
            field=models.BooleanField(default=False, help_text='Indicates if this guest accepts accommodation'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='accept_vip',
            field=models.BooleanField(default=False, help_text='Indicates if this guest accepts VIP status'),
        ),
    ]
