# Generated by Django 5.2.4 on 2025-11-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0015_remove_historicalrsvpsubmission_accept_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpsubmission',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalrsvpsubmission',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
    ]
