# Generated by Django 5.2.4 on 2025-11-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0016_historicalrsvpsubmission_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpbooleananswer',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='rsvpbooleananswer',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='rsvpinputanswer',
            name='question_text',
        ),
    ]
