# Generated by Django 5.2.4 on 2025-11-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0019_alter_historicalrsvpbooleananswer_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpbooleananswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrsvpinputanswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpbooleananswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpinputanswer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
