# Generated by Django 5.2.4 on 2025-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_rsvpformboolean_delete_rsvpforminput_and_more'),
        ('guestlist', '0021_remove_historicalrsvpinputanswer_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpquestionresponse',
            name='choice_answer',
        ),
        migrations.RemoveField(
            model_name='rsvpquestionresponse',
            name='choice_answer',
        ),
        migrations.AddField(
            model_name='rsvpquestionresponse',
            name='response_choices',
            field=models.ManyToManyField(blank=True, related_name='responses', to='core.rsvpquestionchoice'),
        ),
    ]
