# Generated by Django 5.2.10 on 2026-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0022_remove_historicalrsvpquestionresponse_choice_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguestgroup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
