# Generated by Django 5.2.11 on 2026-02-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('guestlist', '0023_alter_guest_notes_alter_guestgroup_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code for RSVP link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code_guest_group', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='historicalguestgroup',
            name='qr_code',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='QR code for RSVP link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attachments.attachment'),
        ),
    ]
