# Generated by Django 6.0.3 on 2026-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0024_guestgroup_qr_code_historicalguestgroup_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpsubmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
