# Generated by Django 5.2.4 on 2025-07-15 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_is_deleted_listentry_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name'], 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterModelOptions(
            name='listentry',
            options={'ordering': ['order', 'item'], 'verbose_name_plural': 'List Entries'},
        ),
        migrations.RemoveField(
            model_name='list',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='list',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listentry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_list_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_list_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='item',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_list'),
        ),
        migrations.AddConstraint(
            model_name='listentry',
            constraint=models.UniqueConstraint(fields=('item', 'list'), name='unique_list_entry_item_list'),
        ),
    ]
