# Generated by Django 5.2.4 on 2025-07-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_options_alter_listentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
