# Generated by Django 5.2.4 on 2025-07-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_listentry_additional_price_listentry_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='expense_item',
            field=models.BooleanField(default=False, help_text='Indicates if this entry is associated with an expense entry'),
        ),
    ]
