# Generated by Django 5.2.4 on 2025-07-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_listentry_associated_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listentry',
            name='expense_item',
        ),
        migrations.AddField(
            model_name='listentry',
            name='purchased',
            field=models.BooleanField(default=False, help_text='Indicates if this entry was already purchased'),
        ),
    ]
