# Generated by Django 5.2.4 on 2025-07-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_listentry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='url',
            field=models.URLField(blank=True, help_text='URL for this item, e.g., a link to an online store or product page', max_length=1000, null=True),
        ),
    ]
