# Generated by Django 5.2.4 on 2025-07-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_listentry_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for this entry, regardless of quantity', max_digits=10),
        ),
        migrations.AddField(
            model_name='listentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listentry',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
