# Generated by Django 5.2.4 on 2025-07-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_unique_expense_item_category'),
        ('list', '0006_listentry_expense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='associated_expense',
            field=models.ForeignKey(blank=True, help_text='The associated expense item if this entry is marked as an expense item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_entries', to='expenses.expense'),
        ),
    ]
