# Generated by Django 5.2.4 on 2025-07-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_category'),
        ('list', '0008_remove_listentry_expense_item_listentry_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The vendor from which this item was/will be purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_list_entries', to='contacts.contact'),
        ),
    ]
