# Generated by Django 5.2.4 on 2025-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_listentry_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='url',
            field=models.URLField(blank=True, help_text='URL for this item, e.g., a link to an online store or product page', null=True),
        ),
    ]
