# Generated by Django 5.2.4 on 2025-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_historicallist_historicallistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistentry',
            name='image',
            field=models.TextField(blank=True, help_text='Image associated with this list entry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listentry',
            name='image',
            field=models.ImageField(blank=True, help_text='Image associated with this list entry', null=True, upload_to='list_entries/images/'),
        ),
    ]
