# Generated by Django 5.2.4 on 2025-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
