# Generated by Django 5.2.4 on 2025-09-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_historicalcategory_historicalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for this expense, regardless of quantity', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for this expense, regardless of quantity', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
