# Generated by Django 5.2.4 on 2025-10-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_historicalfile_contact_and_more'),
        ('expenses', '0008_expense_additional_price_expense_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
    ]
