# Generated by Django 5.2.4 on 2025-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, help_text='Contact category (e.g., Vendor, Guest, Venue)', max_length=100, null=True),
        ),
    ]
