# Generated by Django 5.2.4 on 2025-09-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0002_alter_deadline_options_remove_deadline_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlinelist',
            options={'ordering': ['name'], 'verbose_name_plural': 'Deadline Lists'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeadlinelist',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical deadline list', 'verbose_name_plural': 'historical Deadline Lists'},
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadline_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='deadline.deadlinelist'),
        ),
    ]
