# Generated by Django 5.2.4 on 2025-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0002_guestgroup_associated_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='overnight',
            field=models.BooleanField(default=False, help_text='Indicates if this guest will use overnight accommodation'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='overnight',
            field=models.BooleanField(default=False, help_text='Indicates if this guest will use overnight accommodation'),
        ),
    ]
