# Generated by Django 5.2.4 on 2025-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0004_guest_responded_historicalguest_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='rsvp_code',
            field=models.CharField(help_text='Unique code for RSVP tracking', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalguestgroup',
            name='rsvp_code',
            field=models.CharField(help_text='Unique code for RSVP tracking', max_length=10, null=True),
        ),
    ]
