# Generated by Django 5.2.4 on 2025-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0005_guestgroup_rsvp_code_historicalguestgroup_rsvp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='address_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='historicalguestgroup',
            name='address_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
