# Generated by Django 5.2.4 on 2025-11-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0006_guestgroup_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='address_two',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalguestgroup',
            name='address_two',
            field=models.TextField(blank=True),
        ),
    ]
