# Generated by Django 5.2.4 on 2025-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0007_guestgroup_address_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='vip',
            field=models.BooleanField(default=False, help_text='Indicates if this guest is a VIP'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='vip',
            field=models.BooleanField(default=False, help_text='Indicates if this guest is a VIP'),
        ),
    ]
