# Generated by Django 5.2.4 on 2025-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0008_guest_vip_historicalguest_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='Guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='Guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='first_name',
            field=models.CharField(default='Guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='last_name',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
