# Generated by Django 5.2.4 on 2025-11-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0011_remove_historicalrsvpsubmission_attending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='overnight',
            new_name='accommodation',
        ),
        migrations.RenameField(
            model_name='historicalguest',
            old_name='overnight',
            new_name='accommodation',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='overnight',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='overnight',
        ),
        migrations.AddField(
            model_name='historicalrsvpsubmission',
            name='accept_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrsvpsubmission',
            name='accept_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='accept_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='accept_vip',
            field=models.BooleanField(default=False),
        ),
    ]
