# Generated by Django 5.2.4 on 2025-11-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0012_rename_overnight_guest_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvpsubmission',
            unique_together={('guest_group',)},
        ),
    ]
