# Generated by Django 5.2.4 on 2025-11-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0013_alter_rsvpsubmission_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='response_notes',
        ),
        migrations.RemoveField(
            model_name='historicalguest',
            name='response_notes',
        ),
    ]
