# Generated by Django 5.2.4 on 2025-11-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestlist', '0018_alter_historicalrsvpbooleananswer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrsvpbooleananswer',
            name='value',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rsvpbooleananswer',
            name='value',
            field=models.BooleanField(null=True),
        ),
    ]
