# Generated by Django 5.2.4 on 2025-11-15 22:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_historicalrsvpforminput_created_by_and_more'),
        ('guestlist', '0020_historicalrsvpbooleananswer_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='rsvpbooleananswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rsvpbooleananswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rsvpbooleananswer',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='rsvpinputanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rsvpinputanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rsvpinputanswer',
            name='submission',
        ),
        migrations.CreateModel(
            name='HistoricalRsvpQuestionResponse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('choice_answer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.rsvpquestionchoice')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.rsvpquestion')),
                ('submission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guestlist.rsvpsubmission')),
            ],
            options={
                'verbose_name': 'historical rsvp question response',
                'verbose_name_plural': 'historical rsvp question responses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RsvpQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('choice_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='core.rsvpquestionchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.rsvpquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='guestlist.rsvpsubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpBooleanAnswer',
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpInputAnswer',
        ),
        migrations.DeleteModel(
            name='RsvpBooleanAnswer',
        ),
        migrations.DeleteModel(
            name='RsvpInputAnswer',
        ),
    ]
