# Generated by Django 5.2.4 on 2025-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicalinspiration_inspiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='file',
            field=models.ImageField(blank=True, help_text='Upload a file related to the inspiration board (optional)', null=True, upload_to='inspirations/'),
        ),
    ]
