# Generated by Django 5.2.4 on 2025-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inspiration_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinspiration',
            name='file',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='file',
        ),
        migrations.AddField(
            model_name='historicalinspiration',
            name='image',
            field=models.TextField(blank=True, help_text='Upload an image related to the inspiration board (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image related to the inspiration board (optional)', null=True, upload_to='inspirations/'),
        ),
    ]
