# Generated by Django 5.2.4 on 2025-10-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_rsvpformboolean_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpformboolean',
            name='setting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.weddingsettings'),
        ),
        migrations.AddField(
            model_name='rsvpformboolean',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_form_booleans', to='core.weddingsettings'),
        ),
    ]
