# Generated by Django 5.2.4 on 2025-10-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalrsvpformboolean_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
