# Generated by Django 5.2.4 on 2025-11-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_weddingsettings_rsvp_accept_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_attending_label',
            field=models.CharField(default="I'll be there!", max_length=100),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_overnight_label',
            field=models.CharField(default="I'll spend the weekend at the lodge", max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_attending_label',
            field=models.CharField(default="I'll be there!", max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_overnight_label',
            field=models.CharField(default="I'll spend the weekend at the lodge", max_length=100),
        ),
    ]
