# Generated by Django 5.2.4 on 2025-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalweddingsettings_rsvp_attending_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_accept_intro',
            field=models.TextField(blank=True, default="We're so excited that you can make it!", null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_accept_intro',
            field=models.TextField(blank=True, default="We're so excited that you can make it!", null=True),
        ),
    ]
