# Generated by Django 5.2.4 on 2025-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historicalweddingsettings_rsvp_accept_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(blank=True, default='Please let us know if you will need accommodation during the wedding weekend.', null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(blank=True, default='Please let us know if you will need accommodation during the wedding weekend.', null=True),
        ),
    ]
