# Generated by Django 5.2.4 on 2025-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historicalweddingsettings_rsvp_accommodation_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_accept_success_message',
            field=models.TextField(default='Thank you for your RSVP! We look forward to celebrating with you.'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_decline_success_message',
            field=models.TextField(default="Thank you for letting us know. We'll miss you at the celebration."),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_accept_success_message',
            field=models.TextField(default='Thank you for your RSVP! We look forward to celebrating with you.'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_decline_success_message',
            field=models.TextField(default="Thank you for letting us know. We'll miss you at the celebration."),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_accept_intro',
            field=models.TextField(default="We're so excited that you can make it!"),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(default='Please let us know if you will need accommodation during the wedding weekend.'),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_accept_intro',
            field=models.TextField(default="We're so excited that you can make it!"),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(default='Please let us know if you will need accommodation during the wedding weekend.'),
        ),
    ]
