# Generated by Django 5.2.4 on 2025-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_historicalrsvpforminput_rsvpforminput'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='default_data_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='default_data_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
