# Generated by Django 5.2.4 on 2025-11-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_historicalweddingsettings_standard_group_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_show_accommodation_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_show_vip_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_vip_intro',
            field=models.TextField(default='Please let us know if you will be joining us for the VIP overnight experience.'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_show_accommodation_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_show_vip_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_vip_intro',
            field=models.TextField(default='Please let us know if you will be joining us for the VIP overnight experience.'),
        ),
    ]
