# Generated by Django 5.2.4 on 2025-11-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_rsvp_overnight_label_historicalweddingsettings_rsvp_accommodation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_email_update_label',
            field=models.CharField(default='Yes, keep me updated via email', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_enable_email_updates',
            field=models.BooleanField(default=False, help_text='Allow guests to opt-in for email updates about the wedding'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_email_update_label',
            field=models.CharField(default='Yes, keep me updated via email', max_length=150),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_enable_email_updates',
            field=models.BooleanField(default=False, help_text='Allow guests to opt-in for email updates about the wedding'),
        ),
    ]
