# Generated by Django 5.2.4 on 2025-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_historicalrsvpforminput_created_by_and_more'),
        ('guestlist', '0021_remove_historicalrsvpinputanswer_history_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RsvpFormBoolean',
        ),
        migrations.DeleteModel(
            name='RsvpFormInput',
        ),
        migrations.AddConstraint(
            model_name='rsvpquestion',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_rsvp_question'),
        ),
    ]
