# Generated by Django 5.2.4 on 2025-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_rsvpquestionchoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrsvpquestionchoice',
            name='choice_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rsvpquestionchoice',
            name='choice_text',
            field=models.CharField(max_length=500),
        ),
    ]
