# Generated by Django 5.2.4 on 2025-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_historicalrsvpquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpquestionchoice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsvpquestionchoice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
