# Generated by Django 6.0.6 on 2026-08-03 23:10

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(upload_to='photos/')),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/')),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Uploading', 'Uploading'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Uploaded Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUploadedPhoto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('photo_file', models.TextField(max_length=100)),
                ('thumbnail_file', models.TextField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Uploading', 'Uploading'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical uploaded photo',
                'verbose_name_plural': 'historical Uploaded Photos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
