# Generated by Django 6.0.6 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedphoto",
            name="camera",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedphoto",
            name="checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="historicaluploadedphoto",
            name="camera",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaluploadedphoto",
            name="checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
