# Generated by Django 6.0.6 on 2026-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_uploadedphoto_camera_uploadedphoto_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluploadedphoto',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
