/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContactCreateSchema, ContactSchema, ContactUpdateSchema, PagedContactSchema } from "../models/index";
import {
    ContactCreateSchemaFromJSON,
    ContactCreateSchemaToJSON,
    ContactSchemaFromJSON,
    ContactSchemaToJSON,
    ContactUpdateSchemaFromJSON,
    ContactUpdateSchemaToJSON,
    PagedContactSchemaFromJSON,
    PagedContactSchemaToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ContactsApiCreateContactRequest {
    contactCreateSchema: ContactCreateSchema;
}

export interface ContactsApiDeleteContactRequest {
    contactId: string;
}

export interface ContactsApiGetContactRequest {
    contactId: string;
}

export interface ContactsApiListContactsRequest {
    category?: string | null;
    search?: string | null;
    page?: number;
    pageSize?: number | null;
}

export interface ContactsApiUpdateContactRequest {
    contactId: string;
    contactUpdateSchema: ContactUpdateSchema;
}

/**
 *
 */
export class ContactsApi extends runtime.BaseAPI {
    /**
     * Create a new contact
     * Create Contact
     */
    async contactsApiCreateContactRaw(
        requestParameters: ContactsApiCreateContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ContactSchema>> {
        if (requestParameters["contactCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "contactCreateSchema",
                'Required parameter "contactCreateSchema" was null or undefined when calling contactsApiCreateContact().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/contacts/contacts`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: ContactCreateSchemaToJSON(requestParameters["contactCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new contact
     * Create Contact
     */
    async contactsApiCreateContact(
        requestParameters: ContactsApiCreateContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ContactSchema> {
        const response = await this.contactsApiCreateContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft delete a contact
     * Delete Contact
     */
    async contactsApiDeleteContactRaw(
        requestParameters: ContactsApiDeleteContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["contactId"] == null) {
            throw new runtime.RequiredError(
                "contactId",
                'Required parameter "contactId" was null or undefined when calling contactsApiDeleteContact().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/contacts/contacts/{contact_id}`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters["contactId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a contact
     * Delete Contact
     */
    async contactsApiDeleteContact(
        requestParameters: ContactsApiDeleteContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.contactsApiDeleteContactRaw(requestParameters, initOverrides);
    }

    /**
     * Get a specific contact by ID
     * Get Contact
     */
    async contactsApiGetContactRaw(
        requestParameters: ContactsApiGetContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ContactSchema>> {
        if (requestParameters["contactId"] == null) {
            throw new runtime.RequiredError(
                "contactId",
                'Required parameter "contactId" was null or undefined when calling contactsApiGetContact().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/contacts/contacts/{contact_id}`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters["contactId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific contact by ID
     * Get Contact
     */
    async contactsApiGetContact(
        requestParameters: ContactsApiGetContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ContactSchema> {
        const response = await this.contactsApiGetContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all contacts (non-deleted) with filtering
     * List Contacts
     */
    async contactsApiListContactsRaw(
        requestParameters: ContactsApiListContactsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedContactSchema>> {
        const queryParameters: any = {};

        if (requestParameters["category"] != null) {
            queryParameters["category"] = requestParameters["category"];
        }

        if (requestParameters["search"] != null) {
            queryParameters["search"] = requestParameters["search"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/contacts/contacts`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedContactSchemaFromJSON(jsonValue));
    }

    /**
     * List all contacts (non-deleted) with filtering
     * List Contacts
     */
    async contactsApiListContacts(
        requestParameters: ContactsApiListContactsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedContactSchema> {
        const response = await this.contactsApiListContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a contact
     * Update Contact
     */
    async contactsApiUpdateContactRaw(
        requestParameters: ContactsApiUpdateContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ContactSchema>> {
        if (requestParameters["contactId"] == null) {
            throw new runtime.RequiredError(
                "contactId",
                'Required parameter "contactId" was null or undefined when calling contactsApiUpdateContact().',
            );
        }

        if (requestParameters["contactUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "contactUpdateSchema",
                'Required parameter "contactUpdateSchema" was null or undefined when calling contactsApiUpdateContact().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/contacts/contacts/{contact_id}`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters["contactId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: ContactUpdateSchemaToJSON(requestParameters["contactUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactSchemaFromJSON(jsonValue));
    }

    /**
     * Update a contact
     * Update Contact
     */
    async contactsApiUpdateContact(
        requestParameters: ContactsApiUpdateContactRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ContactSchema> {
        const response = await this.contactsApiUpdateContactRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
