/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
    CategoryContentSchema,
    IdeaCreateSchema,
    IdeaSchema,
    IdeaUpdateSchema,
    InspirationCreateSchema,
    InspirationSchema,
    InspirationUpdateSchema,
    PagedIdeaSchema,
    PagedInspirationSchema,
    PagedQuestionSchema,
    PagedRsvpQuestionSchema,
    PagedTipsSchema,
    QuestionCreateSchema,
    QuestionSchema,
    QuestionURLCreateSchema,
    QuestionURLSchema,
    QuestionURLUpdateSchema,
    QuestionUpdateSchema,
    RsvpQuestionChoiceCreateSchema,
    RsvpQuestionChoiceSchema,
    RsvpQuestionChoiceUpdateSchema,
    RsvpQuestionCreateSchema,
    RsvpQuestionSchema,
    RsvpQuestionUpdateSchema,
    TipsCreateSchema,
    TipsSchema,
    TipsUpdateSchema,
    WeddingSettingsSchema,
    WeddingSettingsUpdateSchema,
} from "../models/index";
import {
    CategoryContentSchemaFromJSON,
    CategoryContentSchemaToJSON,
    IdeaCreateSchemaFromJSON,
    IdeaCreateSchemaToJSON,
    IdeaSchemaFromJSON,
    IdeaSchemaToJSON,
    IdeaUpdateSchemaFromJSON,
    IdeaUpdateSchemaToJSON,
    InspirationCreateSchemaFromJSON,
    InspirationCreateSchemaToJSON,
    InspirationSchemaFromJSON,
    InspirationSchemaToJSON,
    InspirationUpdateSchemaFromJSON,
    InspirationUpdateSchemaToJSON,
    PagedIdeaSchemaFromJSON,
    PagedIdeaSchemaToJSON,
    PagedInspirationSchemaFromJSON,
    PagedInspirationSchemaToJSON,
    PagedQuestionSchemaFromJSON,
    PagedQuestionSchemaToJSON,
    PagedRsvpQuestionSchemaFromJSON,
    PagedRsvpQuestionSchemaToJSON,
    PagedTipsSchemaFromJSON,
    PagedTipsSchemaToJSON,
    QuestionCreateSchemaFromJSON,
    QuestionCreateSchemaToJSON,
    QuestionSchemaFromJSON,
    QuestionSchemaToJSON,
    QuestionURLCreateSchemaFromJSON,
    QuestionURLCreateSchemaToJSON,
    QuestionURLSchemaFromJSON,
    QuestionURLSchemaToJSON,
    QuestionURLUpdateSchemaFromJSON,
    QuestionURLUpdateSchemaToJSON,
    QuestionUpdateSchemaFromJSON,
    QuestionUpdateSchemaToJSON,
    RsvpQuestionChoiceCreateSchemaFromJSON,
    RsvpQuestionChoiceCreateSchemaToJSON,
    RsvpQuestionChoiceSchemaFromJSON,
    RsvpQuestionChoiceSchemaToJSON,
    RsvpQuestionChoiceUpdateSchemaFromJSON,
    RsvpQuestionChoiceUpdateSchemaToJSON,
    RsvpQuestionCreateSchemaFromJSON,
    RsvpQuestionCreateSchemaToJSON,
    RsvpQuestionSchemaFromJSON,
    RsvpQuestionSchemaToJSON,
    RsvpQuestionUpdateSchemaFromJSON,
    RsvpQuestionUpdateSchemaToJSON,
    TipsCreateSchemaFromJSON,
    TipsCreateSchemaToJSON,
    TipsSchemaFromJSON,
    TipsSchemaToJSON,
    TipsUpdateSchemaFromJSON,
    TipsUpdateSchemaToJSON,
    WeddingSettingsSchemaFromJSON,
    WeddingSettingsSchemaToJSON,
    WeddingSettingsUpdateSchemaFromJSON,
    WeddingSettingsUpdateSchemaToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface CoreApiCreateIdeaRequest {
    ideaCreateSchema: IdeaCreateSchema;
}

export interface CoreApiCreateInspirationRequest {
    inspirationCreateSchema: InspirationCreateSchema;
}

export interface CoreApiCreateQuestionRequest {
    questionCreateSchema: QuestionCreateSchema;
}

export interface CoreApiCreateQuestionUrlRequest {
    questionURLCreateSchema: QuestionURLCreateSchema;
}

export interface CoreApiCreateRsvpQuestionRequest {
    rsvpQuestionCreateSchema: RsvpQuestionCreateSchema;
}

export interface CoreApiCreateRsvpQuestionChoiceRequest {
    rsvpQuestionChoiceCreateSchema: RsvpQuestionChoiceCreateSchema;
}

export interface CoreApiCreateTipRequest {
    tipsCreateSchema: TipsCreateSchema;
}

export interface CoreApiDeleteIdeaRequest {
    ideaId: string;
}

export interface CoreApiDeleteInspirationRequest {
    inspirationId: string;
}

export interface CoreApiDeleteInspirationImageRequest {
    inspirationId: string;
}

export interface CoreApiDeleteQuestionRequest {
    questionId: string;
}

export interface CoreApiDeleteQuestionUrlRequest {
    urlId: string;
}

export interface CoreApiDeleteRsvpQuestionRequest {
    questionId: string;
}

export interface CoreApiDeleteRsvpQuestionChoiceRequest {
    choiceId: string;
}

export interface CoreApiDeleteTipRequest {
    tipId: string;
}

export interface CoreApiGetCategoriesContentRequest {
    publishedOnly?: boolean;
}

export interface CoreApiGetIdeaRequest {
    ideaId: string;
}

export interface CoreApiGetInspirationRequest {
    inspirationId: string;
}

export interface CoreApiGetQuestionRequest {
    questionId: string;
}

export interface CoreApiGetQuestionUrlRequest {
    urlId: string;
}

export interface CoreApiGetRsvpQuestionRequest {
    questionId: string;
}

export interface CoreApiGetRsvpQuestionChoiceRequest {
    choiceId: string;
}

export interface CoreApiGetTipRequest {
    tipId: string;
}

export interface CoreApiListIdeasRequest {
    name?: string | null;
    page?: number;
    pageSize?: number | null;
}

export interface CoreApiListInspirationsRequest {
    name?: string | null;
    page?: number;
    pageSize?: number | null;
}

export interface CoreApiListQuestionUrlsRequest {
    questionId?: string | null;
}

export interface CoreApiListQuestionsRequest {
    category?: string | null;
    published?: boolean | null;
    page?: number;
    pageSize?: number | null;
}

export interface CoreApiListRsvpQuestionsRequest {
    published?: boolean | null;
    questionType?: string | null;
    page?: number;
    pageSize?: number | null;
}

export interface CoreApiListTipsRequest {
    category?: string | null;
    published?: boolean | null;
    page?: number;
    pageSize?: number | null;
}

export interface CoreApiUpdateIdeaRequest {
    ideaId: string;
    ideaUpdateSchema: IdeaUpdateSchema;
}

export interface CoreApiUpdateInspirationRequest {
    inspirationId: string;
    inspirationUpdateSchema: InspirationUpdateSchema;
}

export interface CoreApiUpdateQuestionRequest {
    questionId: string;
    questionUpdateSchema: QuestionUpdateSchema;
}

export interface CoreApiUpdateQuestionUrlRequest {
    urlId: string;
    questionURLUpdateSchema: QuestionURLUpdateSchema;
}

export interface CoreApiUpdateRsvpQuestionRequest {
    questionId: string;
    rsvpQuestionUpdateSchema: RsvpQuestionUpdateSchema;
}

export interface CoreApiUpdateRsvpQuestionChoiceRequest {
    choiceId: string;
    rsvpQuestionChoiceUpdateSchema: RsvpQuestionChoiceUpdateSchema;
}

export interface CoreApiUpdateTipRequest {
    tipId: string;
    tipsUpdateSchema: TipsUpdateSchema;
}

export interface CoreApiUpdateWeddingSettingsRequest {
    weddingSettingsUpdateSchema: WeddingSettingsUpdateSchema;
}

export interface CoreApiUploadInspirationImageRequest {
    inspirationId: string;
    image: Blob;
}

/**
 *
 */
export class CoreApi extends runtime.BaseAPI {
    /**
     * Create a new idea
     * Create Idea
     */
    async coreApiCreateIdeaRaw(
        requestParameters: CoreApiCreateIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<IdeaSchema>> {
        if (requestParameters["ideaCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "ideaCreateSchema",
                'Required parameter "ideaCreateSchema" was null or undefined when calling coreApiCreateIdea().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/ideas`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: IdeaCreateSchemaToJSON(requestParameters["ideaCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => IdeaSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new idea
     * Create Idea
     */
    async coreApiCreateIdea(
        requestParameters: CoreApiCreateIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<IdeaSchema> {
        const response = await this.coreApiCreateIdeaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new inspiration
     * Create Inspiration
     */
    async coreApiCreateInspirationRaw(
        requestParameters: CoreApiCreateInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<InspirationSchema>> {
        if (requestParameters["inspirationCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "inspirationCreateSchema",
                'Required parameter "inspirationCreateSchema" was null or undefined when calling coreApiCreateInspiration().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: InspirationCreateSchemaToJSON(requestParameters["inspirationCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => InspirationSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new inspiration
     * Create Inspiration
     */
    async coreApiCreateInspiration(
        requestParameters: CoreApiCreateInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<InspirationSchema> {
        const response = await this.coreApiCreateInspirationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new question
     * Create Question
     */
    async coreApiCreateQuestionRaw(
        requestParameters: CoreApiCreateQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionSchema>> {
        if (requestParameters["questionCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "questionCreateSchema",
                'Required parameter "questionCreateSchema" was null or undefined when calling coreApiCreateQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/questions`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: QuestionCreateSchemaToJSON(requestParameters["questionCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new question
     * Create Question
     */
    async coreApiCreateQuestion(
        requestParameters: CoreApiCreateQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionSchema> {
        const response = await this.coreApiCreateQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new question URL
     * Create Question Url
     */
    async coreApiCreateQuestionUrlRaw(
        requestParameters: CoreApiCreateQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionURLSchema>> {
        if (requestParameters["questionURLCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "questionURLCreateSchema",
                'Required parameter "questionURLCreateSchema" was null or undefined when calling coreApiCreateQuestionUrl().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/question-urls`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: QuestionURLCreateSchemaToJSON(requestParameters["questionURLCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionURLSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new question URL
     * Create Question Url
     */
    async coreApiCreateQuestionUrl(
        requestParameters: CoreApiCreateQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionURLSchema> {
        const response = await this.coreApiCreateQuestionUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new RSVP question
     * Create Rsvp Question
     */
    async coreApiCreateRsvpQuestionRaw(
        requestParameters: CoreApiCreateRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionSchema>> {
        if (requestParameters["rsvpQuestionCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "rsvpQuestionCreateSchema",
                'Required parameter "rsvpQuestionCreateSchema" was null or undefined when calling coreApiCreateRsvpQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-questions`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: RsvpQuestionCreateSchemaToJSON(requestParameters["rsvpQuestionCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new RSVP question
     * Create Rsvp Question
     */
    async coreApiCreateRsvpQuestion(
        requestParameters: CoreApiCreateRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionSchema> {
        const response = await this.coreApiCreateRsvpQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new RSVP question choice
     * Create Rsvp Question Choice
     */
    async coreApiCreateRsvpQuestionChoiceRaw(
        requestParameters: CoreApiCreateRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionChoiceSchema>> {
        if (requestParameters["rsvpQuestionChoiceCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "rsvpQuestionChoiceCreateSchema",
                'Required parameter "rsvpQuestionChoiceCreateSchema" was null or undefined when calling coreApiCreateRsvpQuestionChoice().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-question-choices`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: RsvpQuestionChoiceCreateSchemaToJSON(requestParameters["rsvpQuestionChoiceCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionChoiceSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new RSVP question choice
     * Create Rsvp Question Choice
     */
    async coreApiCreateRsvpQuestionChoice(
        requestParameters: CoreApiCreateRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionChoiceSchema> {
        const response = await this.coreApiCreateRsvpQuestionChoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new tip
     * Create Tip
     */
    async coreApiCreateTipRaw(
        requestParameters: CoreApiCreateTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TipsSchema>> {
        if (requestParameters["tipsCreateSchema"] == null) {
            throw new runtime.RequiredError(
                "tipsCreateSchema",
                'Required parameter "tipsCreateSchema" was null or undefined when calling coreApiCreateTip().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/tips`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: TipsCreateSchemaToJSON(requestParameters["tipsCreateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => TipsSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new tip
     * Create Tip
     */
    async coreApiCreateTip(
        requestParameters: CoreApiCreateTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TipsSchema> {
        const response = await this.coreApiCreateTipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft delete an idea
     * Delete Idea
     */
    async coreApiDeleteIdeaRaw(
        requestParameters: CoreApiDeleteIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["ideaId"] == null) {
            throw new runtime.RequiredError(
                "ideaId",
                'Required parameter "ideaId" was null or undefined when calling coreApiDeleteIdea().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/ideas/{idea_id}`;
        urlPath = urlPath.replace(`{${"idea_id"}}`, encodeURIComponent(String(requestParameters["ideaId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete an idea
     * Delete Idea
     */
    async coreApiDeleteIdea(
        requestParameters: CoreApiDeleteIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteIdeaRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete an inspiration
     * Delete Inspiration
     */
    async coreApiDeleteInspirationRaw(
        requestParameters: CoreApiDeleteInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["inspirationId"] == null) {
            throw new runtime.RequiredError(
                "inspirationId",
                'Required parameter "inspirationId" was null or undefined when calling coreApiDeleteInspiration().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations/{inspiration_id}`;
        urlPath = urlPath.replace(
            `{${"inspiration_id"}}`,
            encodeURIComponent(String(requestParameters["inspirationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete an inspiration
     * Delete Inspiration
     */
    async coreApiDeleteInspiration(
        requestParameters: CoreApiDeleteInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteInspirationRaw(requestParameters, initOverrides);
    }

    /**
     * Delete image from an inspiration
     * Delete Inspiration Image
     */
    async coreApiDeleteInspirationImageRaw(
        requestParameters: CoreApiDeleteInspirationImageRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["inspirationId"] == null) {
            throw new runtime.RequiredError(
                "inspirationId",
                'Required parameter "inspirationId" was null or undefined when calling coreApiDeleteInspirationImage().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations/{inspiration_id}/image`;
        urlPath = urlPath.replace(
            `{${"inspiration_id"}}`,
            encodeURIComponent(String(requestParameters["inspirationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete image from an inspiration
     * Delete Inspiration Image
     */
    async coreApiDeleteInspirationImage(
        requestParameters: CoreApiDeleteInspirationImageRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteInspirationImageRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete a question
     * Delete Question
     */
    async coreApiDeleteQuestionRaw(
        requestParameters: CoreApiDeleteQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiDeleteQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a question
     * Delete Question
     */
    async coreApiDeleteQuestion(
        requestParameters: CoreApiDeleteQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteQuestionRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete a question URL
     * Delete Question Url
     */
    async coreApiDeleteQuestionUrlRaw(
        requestParameters: CoreApiDeleteQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["urlId"] == null) {
            throw new runtime.RequiredError(
                "urlId",
                'Required parameter "urlId" was null or undefined when calling coreApiDeleteQuestionUrl().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/question-urls/{url_id}`;
        urlPath = urlPath.replace(`{${"url_id"}}`, encodeURIComponent(String(requestParameters["urlId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a question URL
     * Delete Question Url
     */
    async coreApiDeleteQuestionUrl(
        requestParameters: CoreApiDeleteQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteQuestionUrlRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete an RSVP question
     * Delete Rsvp Question
     */
    async coreApiDeleteRsvpQuestionRaw(
        requestParameters: CoreApiDeleteRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiDeleteRsvpQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete an RSVP question
     * Delete Rsvp Question
     */
    async coreApiDeleteRsvpQuestion(
        requestParameters: CoreApiDeleteRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteRsvpQuestionRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete an RSVP question choice
     * Delete Rsvp Question Choice
     */
    async coreApiDeleteRsvpQuestionChoiceRaw(
        requestParameters: CoreApiDeleteRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["choiceId"] == null) {
            throw new runtime.RequiredError(
                "choiceId",
                'Required parameter "choiceId" was null or undefined when calling coreApiDeleteRsvpQuestionChoice().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-question-choices/{choice_id}`;
        urlPath = urlPath.replace(`{${"choice_id"}}`, encodeURIComponent(String(requestParameters["choiceId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete an RSVP question choice
     * Delete Rsvp Question Choice
     */
    async coreApiDeleteRsvpQuestionChoice(
        requestParameters: CoreApiDeleteRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteRsvpQuestionChoiceRaw(requestParameters, initOverrides);
    }

    /**
     * Soft delete a tip
     * Delete Tip
     */
    async coreApiDeleteTipRaw(
        requestParameters: CoreApiDeleteTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["tipId"] == null) {
            throw new runtime.RequiredError(
                "tipId",
                'Required parameter "tipId" was null or undefined when calling coreApiDeleteTip().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/tips/{tip_id}`;
        urlPath = urlPath.replace(`{${"tip_id"}}`, encodeURIComponent(String(requestParameters["tipId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a tip
     * Delete Tip
     */
    async coreApiDeleteTip(
        requestParameters: CoreApiDeleteTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.coreApiDeleteTipRaw(requestParameters, initOverrides);
    }

    /**
     * Get all categories with their associated questions and tips
     * Get Categories Content
     */
    async coreApiGetCategoriesContentRaw(
        requestParameters: CoreApiGetCategoriesContentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<CategoryContentSchema>>> {
        const queryParameters: any = {};

        if (requestParameters["publishedOnly"] != null) {
            queryParameters["published_only"] = requestParameters["publishedOnly"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-categories-content`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryContentSchemaFromJSON));
    }

    /**
     * Get all categories with their associated questions and tips
     * Get Categories Content
     */
    async coreApiGetCategoriesContent(
        requestParameters: CoreApiGetCategoriesContentRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<CategoryContentSchema>> {
        const response = await this.coreApiGetCategoriesContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific idea by ID
     * Get Idea
     */
    async coreApiGetIdeaRaw(
        requestParameters: CoreApiGetIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<IdeaSchema>> {
        if (requestParameters["ideaId"] == null) {
            throw new runtime.RequiredError(
                "ideaId",
                'Required parameter "ideaId" was null or undefined when calling coreApiGetIdea().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/ideas/{idea_id}`;
        urlPath = urlPath.replace(`{${"idea_id"}}`, encodeURIComponent(String(requestParameters["ideaId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => IdeaSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific idea by ID
     * Get Idea
     */
    async coreApiGetIdea(
        requestParameters: CoreApiGetIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<IdeaSchema> {
        const response = await this.coreApiGetIdeaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific inspiration by ID
     * Get Inspiration
     */
    async coreApiGetInspirationRaw(
        requestParameters: CoreApiGetInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<InspirationSchema>> {
        if (requestParameters["inspirationId"] == null) {
            throw new runtime.RequiredError(
                "inspirationId",
                'Required parameter "inspirationId" was null or undefined when calling coreApiGetInspiration().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations/{inspiration_id}`;
        urlPath = urlPath.replace(
            `{${"inspiration_id"}}`,
            encodeURIComponent(String(requestParameters["inspirationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => InspirationSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific inspiration by ID
     * Get Inspiration
     */
    async coreApiGetInspiration(
        requestParameters: CoreApiGetInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<InspirationSchema> {
        const response = await this.coreApiGetInspirationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific question by ID
     * Get Question
     */
    async coreApiGetQuestionRaw(
        requestParameters: CoreApiGetQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionSchema>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiGetQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific question by ID
     * Get Question
     */
    async coreApiGetQuestion(
        requestParameters: CoreApiGetQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionSchema> {
        const response = await this.coreApiGetQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific question URL by ID
     * Get Question Url
     */
    async coreApiGetQuestionUrlRaw(
        requestParameters: CoreApiGetQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionURLSchema>> {
        if (requestParameters["urlId"] == null) {
            throw new runtime.RequiredError(
                "urlId",
                'Required parameter "urlId" was null or undefined when calling coreApiGetQuestionUrl().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/question-urls/{url_id}`;
        urlPath = urlPath.replace(`{${"url_id"}}`, encodeURIComponent(String(requestParameters["urlId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionURLSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific question URL by ID
     * Get Question Url
     */
    async coreApiGetQuestionUrl(
        requestParameters: CoreApiGetQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionURLSchema> {
        const response = await this.coreApiGetQuestionUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific RSVP question by ID
     * Get Rsvp Question
     */
    async coreApiGetRsvpQuestionRaw(
        requestParameters: CoreApiGetRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionSchema>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiGetRsvpQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific RSVP question by ID
     * Get Rsvp Question
     */
    async coreApiGetRsvpQuestion(
        requestParameters: CoreApiGetRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionSchema> {
        const response = await this.coreApiGetRsvpQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific RSVP question choice by ID
     * Get Rsvp Question Choice
     */
    async coreApiGetRsvpQuestionChoiceRaw(
        requestParameters: CoreApiGetRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionChoiceSchema>> {
        if (requestParameters["choiceId"] == null) {
            throw new runtime.RequiredError(
                "choiceId",
                'Required parameter "choiceId" was null or undefined when calling coreApiGetRsvpQuestionChoice().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-question-choices/{choice_id}`;
        urlPath = urlPath.replace(`{${"choice_id"}}`, encodeURIComponent(String(requestParameters["choiceId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionChoiceSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific RSVP question choice by ID
     * Get Rsvp Question Choice
     */
    async coreApiGetRsvpQuestionChoice(
        requestParameters: CoreApiGetRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionChoiceSchema> {
        const response = await this.coreApiGetRsvpQuestionChoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific tip by ID
     * Get Tip
     */
    async coreApiGetTipRaw(
        requestParameters: CoreApiGetTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TipsSchema>> {
        if (requestParameters["tipId"] == null) {
            throw new runtime.RequiredError(
                "tipId",
                'Required parameter "tipId" was null or undefined when calling coreApiGetTip().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/tips/{tip_id}`;
        urlPath = urlPath.replace(`{${"tip_id"}}`, encodeURIComponent(String(requestParameters["tipId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => TipsSchemaFromJSON(jsonValue));
    }

    /**
     * Get a specific tip by ID
     * Get Tip
     */
    async coreApiGetTip(
        requestParameters: CoreApiGetTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TipsSchema> {
        const response = await this.coreApiGetTipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get wedding settings (singleton)
     * Get Wedding Settings
     */
    async coreApiGetWeddingSettingsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<WeddingSettingsSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/wedding-settings`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => WeddingSettingsSchemaFromJSON(jsonValue));
    }

    /**
     * Get wedding settings (singleton)
     * Get Wedding Settings
     */
    async coreApiGetWeddingSettings(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<WeddingSettingsSchema> {
        const response = await this.coreApiGetWeddingSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all ideas (non-deleted)
     * List Ideas
     */
    async coreApiListIdeasRaw(
        requestParameters: CoreApiListIdeasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedIdeaSchema>> {
        const queryParameters: any = {};

        if (requestParameters["name"] != null) {
            queryParameters["name"] = requestParameters["name"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/ideas`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedIdeaSchemaFromJSON(jsonValue));
    }

    /**
     * List all ideas (non-deleted)
     * List Ideas
     */
    async coreApiListIdeas(
        requestParameters: CoreApiListIdeasRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedIdeaSchema> {
        const response = await this.coreApiListIdeasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all inspirations (non-deleted)
     * List Inspirations
     */
    async coreApiListInspirationsRaw(
        requestParameters: CoreApiListInspirationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedInspirationSchema>> {
        const queryParameters: any = {};

        if (requestParameters["name"] != null) {
            queryParameters["name"] = requestParameters["name"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedInspirationSchemaFromJSON(jsonValue));
    }

    /**
     * List all inspirations (non-deleted)
     * List Inspirations
     */
    async coreApiListInspirations(
        requestParameters: CoreApiListInspirationsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedInspirationSchema> {
        const response = await this.coreApiListInspirationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all question URLs (non-deleted), optionally filtered by question_id
     * List Question Urls
     */
    async coreApiListQuestionUrlsRaw(
        requestParameters: CoreApiListQuestionUrlsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<QuestionURLSchema>>> {
        const queryParameters: any = {};

        if (requestParameters["questionId"] != null) {
            queryParameters["question_id"] = requestParameters["questionId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/question-urls`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionURLSchemaFromJSON));
    }

    /**
     * List all question URLs (non-deleted), optionally filtered by question_id
     * List Question Urls
     */
    async coreApiListQuestionUrls(
        requestParameters: CoreApiListQuestionUrlsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<QuestionURLSchema>> {
        const response = await this.coreApiListQuestionUrlsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all questions (non-deleted)
     * List Questions
     */
    async coreApiListQuestionsRaw(
        requestParameters: CoreApiListQuestionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedQuestionSchema>> {
        const queryParameters: any = {};

        if (requestParameters["category"] != null) {
            queryParameters["category"] = requestParameters["category"];
        }

        if (requestParameters["published"] != null) {
            queryParameters["published"] = requestParameters["published"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/questions`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedQuestionSchemaFromJSON(jsonValue));
    }

    /**
     * List all questions (non-deleted)
     * List Questions
     */
    async coreApiListQuestions(
        requestParameters: CoreApiListQuestionsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedQuestionSchema> {
        const response = await this.coreApiListQuestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all RSVP questions (non-deleted)
     * List Rsvp Questions
     */
    async coreApiListRsvpQuestionsRaw(
        requestParameters: CoreApiListRsvpQuestionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedRsvpQuestionSchema>> {
        const queryParameters: any = {};

        if (requestParameters["published"] != null) {
            queryParameters["published"] = requestParameters["published"];
        }

        if (requestParameters["questionType"] != null) {
            queryParameters["question_type"] = requestParameters["questionType"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-questions`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedRsvpQuestionSchemaFromJSON(jsonValue));
    }

    /**
     * List all RSVP questions (non-deleted)
     * List Rsvp Questions
     */
    async coreApiListRsvpQuestions(
        requestParameters: CoreApiListRsvpQuestionsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedRsvpQuestionSchema> {
        const response = await this.coreApiListRsvpQuestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all tips (non-deleted)
     * List Tips
     */
    async coreApiListTipsRaw(
        requestParameters: CoreApiListTipsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PagedTipsSchema>> {
        const queryParameters: any = {};

        if (requestParameters["category"] != null) {
            queryParameters["category"] = requestParameters["category"];
        }

        if (requestParameters["published"] != null) {
            queryParameters["published"] = requestParameters["published"];
        }

        if (requestParameters["page"] != null) {
            queryParameters["page"] = requestParameters["page"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/tips`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedTipsSchemaFromJSON(jsonValue));
    }

    /**
     * List all tips (non-deleted)
     * List Tips
     */
    async coreApiListTips(
        requestParameters: CoreApiListTipsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PagedTipsSchema> {
        const response = await this.coreApiListTipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an idea
     * Update Idea
     */
    async coreApiUpdateIdeaRaw(
        requestParameters: CoreApiUpdateIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<IdeaSchema>> {
        if (requestParameters["ideaId"] == null) {
            throw new runtime.RequiredError(
                "ideaId",
                'Required parameter "ideaId" was null or undefined when calling coreApiUpdateIdea().',
            );
        }

        if (requestParameters["ideaUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "ideaUpdateSchema",
                'Required parameter "ideaUpdateSchema" was null or undefined when calling coreApiUpdateIdea().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/ideas/{idea_id}`;
        urlPath = urlPath.replace(`{${"idea_id"}}`, encodeURIComponent(String(requestParameters["ideaId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: IdeaUpdateSchemaToJSON(requestParameters["ideaUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => IdeaSchemaFromJSON(jsonValue));
    }

    /**
     * Update an idea
     * Update Idea
     */
    async coreApiUpdateIdea(
        requestParameters: CoreApiUpdateIdeaRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<IdeaSchema> {
        const response = await this.coreApiUpdateIdeaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an inspiration
     * Update Inspiration
     */
    async coreApiUpdateInspirationRaw(
        requestParameters: CoreApiUpdateInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<InspirationSchema>> {
        if (requestParameters["inspirationId"] == null) {
            throw new runtime.RequiredError(
                "inspirationId",
                'Required parameter "inspirationId" was null or undefined when calling coreApiUpdateInspiration().',
            );
        }

        if (requestParameters["inspirationUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "inspirationUpdateSchema",
                'Required parameter "inspirationUpdateSchema" was null or undefined when calling coreApiUpdateInspiration().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/inspirations/{inspiration_id}`;
        urlPath = urlPath.replace(
            `{${"inspiration_id"}}`,
            encodeURIComponent(String(requestParameters["inspirationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: InspirationUpdateSchemaToJSON(requestParameters["inspirationUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => InspirationSchemaFromJSON(jsonValue));
    }

    /**
     * Update an inspiration
     * Update Inspiration
     */
    async coreApiUpdateInspiration(
        requestParameters: CoreApiUpdateInspirationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<InspirationSchema> {
        const response = await this.coreApiUpdateInspirationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a question
     * Update Question
     */
    async coreApiUpdateQuestionRaw(
        requestParameters: CoreApiUpdateQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionSchema>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiUpdateQuestion().',
            );
        }

        if (requestParameters["questionUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "questionUpdateSchema",
                'Required parameter "questionUpdateSchema" was null or undefined when calling coreApiUpdateQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: QuestionUpdateSchemaToJSON(requestParameters["questionUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Update a question
     * Update Question
     */
    async coreApiUpdateQuestion(
        requestParameters: CoreApiUpdateQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionSchema> {
        const response = await this.coreApiUpdateQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a question URL
     * Update Question Url
     */
    async coreApiUpdateQuestionUrlRaw(
        requestParameters: CoreApiUpdateQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<QuestionURLSchema>> {
        if (requestParameters["urlId"] == null) {
            throw new runtime.RequiredError(
                "urlId",
                'Required parameter "urlId" was null or undefined when calling coreApiUpdateQuestionUrl().',
            );
        }

        if (requestParameters["questionURLUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "questionURLUpdateSchema",
                'Required parameter "questionURLUpdateSchema" was null or undefined when calling coreApiUpdateQuestionUrl().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/question-urls/{url_id}`;
        urlPath = urlPath.replace(`{${"url_id"}}`, encodeURIComponent(String(requestParameters["urlId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: QuestionURLUpdateSchemaToJSON(requestParameters["questionURLUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionURLSchemaFromJSON(jsonValue));
    }

    /**
     * Update a question URL
     * Update Question Url
     */
    async coreApiUpdateQuestionUrl(
        requestParameters: CoreApiUpdateQuestionUrlRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<QuestionURLSchema> {
        const response = await this.coreApiUpdateQuestionUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an RSVP question
     * Update Rsvp Question
     */
    async coreApiUpdateRsvpQuestionRaw(
        requestParameters: CoreApiUpdateRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionSchema>> {
        if (requestParameters["questionId"] == null) {
            throw new runtime.RequiredError(
                "questionId",
                'Required parameter "questionId" was null or undefined when calling coreApiUpdateRsvpQuestion().',
            );
        }

        if (requestParameters["rsvpQuestionUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "rsvpQuestionUpdateSchema",
                'Required parameter "rsvpQuestionUpdateSchema" was null or undefined when calling coreApiUpdateRsvpQuestion().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-questions/{question_id}`;
        urlPath = urlPath.replace(`{${"question_id"}}`, encodeURIComponent(String(requestParameters["questionId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: RsvpQuestionUpdateSchemaToJSON(requestParameters["rsvpQuestionUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionSchemaFromJSON(jsonValue));
    }

    /**
     * Update an RSVP question
     * Update Rsvp Question
     */
    async coreApiUpdateRsvpQuestion(
        requestParameters: CoreApiUpdateRsvpQuestionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionSchema> {
        const response = await this.coreApiUpdateRsvpQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an RSVP question choice
     * Update Rsvp Question Choice
     */
    async coreApiUpdateRsvpQuestionChoiceRaw(
        requestParameters: CoreApiUpdateRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RsvpQuestionChoiceSchema>> {
        if (requestParameters["choiceId"] == null) {
            throw new runtime.RequiredError(
                "choiceId",
                'Required parameter "choiceId" was null or undefined when calling coreApiUpdateRsvpQuestionChoice().',
            );
        }

        if (requestParameters["rsvpQuestionChoiceUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "rsvpQuestionChoiceUpdateSchema",
                'Required parameter "rsvpQuestionChoiceUpdateSchema" was null or undefined when calling coreApiUpdateRsvpQuestionChoice().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/rsvp-question-choices/{choice_id}`;
        urlPath = urlPath.replace(`{${"choice_id"}}`, encodeURIComponent(String(requestParameters["choiceId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: RsvpQuestionChoiceUpdateSchemaToJSON(requestParameters["rsvpQuestionChoiceUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => RsvpQuestionChoiceSchemaFromJSON(jsonValue));
    }

    /**
     * Update an RSVP question choice
     * Update Rsvp Question Choice
     */
    async coreApiUpdateRsvpQuestionChoice(
        requestParameters: CoreApiUpdateRsvpQuestionChoiceRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RsvpQuestionChoiceSchema> {
        const response = await this.coreApiUpdateRsvpQuestionChoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a tip
     * Update Tip
     */
    async coreApiUpdateTipRaw(
        requestParameters: CoreApiUpdateTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TipsSchema>> {
        if (requestParameters["tipId"] == null) {
            throw new runtime.RequiredError(
                "tipId",
                'Required parameter "tipId" was null or undefined when calling coreApiUpdateTip().',
            );
        }

        if (requestParameters["tipsUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "tipsUpdateSchema",
                'Required parameter "tipsUpdateSchema" was null or undefined when calling coreApiUpdateTip().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/tips/{tip_id}`;
        urlPath = urlPath.replace(`{${"tip_id"}}`, encodeURIComponent(String(requestParameters["tipId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: TipsUpdateSchemaToJSON(requestParameters["tipsUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => TipsSchemaFromJSON(jsonValue));
    }

    /**
     * Update a tip
     * Update Tip
     */
    async coreApiUpdateTip(
        requestParameters: CoreApiUpdateTipRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TipsSchema> {
        const response = await this.coreApiUpdateTipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update wedding settings
     * Update Wedding Settings
     */
    async coreApiUpdateWeddingSettingsRaw(
        requestParameters: CoreApiUpdateWeddingSettingsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<WeddingSettingsSchema>> {
        if (requestParameters["weddingSettingsUpdateSchema"] == null) {
            throw new runtime.RequiredError(
                "weddingSettingsUpdateSchema",
                'Required parameter "weddingSettingsUpdateSchema" was null or undefined when calling coreApiUpdateWeddingSettings().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/core/wedding-settings`;

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: WeddingSettingsUpdateSchemaToJSON(requestParameters["weddingSettingsUpdateSchema"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => WeddingSettingsSchemaFromJSON(jsonValue));
    }

    /**
     * Update wedding settings
     * Update Wedding Settings
     */
    async coreApiUpdateWeddingSettings(
        requestParameters: CoreApiUpdateWeddingSettingsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<WeddingSettingsSchema> {
        const response = await this.coreApiUpdateWeddingSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload or update image for an inspiration
     * Upload Inspiration Image
     */
    async coreApiUploadInspirationImageRaw(
        requestParameters: CoreApiUploadInspirationImageRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<InspirationSchema>> {
        if (requestParameters["inspirationId"] == null) {
            throw new runtime.RequiredError(
                "inspirationId",
                'Required parameter "inspirationId" was null or undefined when calling coreApiUploadInspirationImage().',
            );
        }

        if (requestParameters["image"] == null) {
            throw new runtime.RequiredError(
                "image",
                'Required parameter "image" was null or undefined when calling coreApiUploadInspirationImage().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters["image"] != null) {
            formParams.append("image", requestParameters["image"] as any);
        }

        let urlPath = `/api/core/inspirations/{inspiration_id}/upload-image`;
        urlPath = urlPath.replace(
            `{${"inspiration_id"}}`,
            encodeURIComponent(String(requestParameters["inspirationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => InspirationSchemaFromJSON(jsonValue));
    }

    /**
     * Upload or update image for an inspiration
     * Upload Inspiration Image
     */
    async coreApiUploadInspirationImage(
        requestParameters: CoreApiUploadInspirationImageRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<InspirationSchema> {
        const response = await this.coreApiUploadInspirationImageRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
