/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type {
    CompleteUploadedPhotoResponseSchema,
    CreateUploadedPhotoResponseSchema,
    UploadedPhotoSchema,
} from "../models/index";
import {
    CompleteUploadedPhotoResponseSchemaFromJSON,
    CompleteUploadedPhotoResponseSchemaToJSON,
    CreateUploadedPhotoResponseSchemaFromJSON,
    CreateUploadedPhotoResponseSchemaToJSON,
    UploadedPhotoSchemaFromJSON,
    UploadedPhotoSchemaToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface PhotosApiCompleteUploadedPhotoRequest {
    photoId: string;
}

export interface PhotosApiDownloadUploadedPhotoRequest {
    photoId: string;
}

/**
 *
 */
export class UploadedPhotosApi extends runtime.BaseAPI {
    /**
     * Process the uploaded photo
     * Complete Uploaded Photo
     */
    async photosApiCompleteUploadedPhotoRaw(
        requestParameters: PhotosApiCompleteUploadedPhotoRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CompleteUploadedPhotoResponseSchema>> {
        if (requestParameters["photoId"] == null) {
            throw new runtime.RequiredError(
                "photoId",
                'Required parameter "photoId" was null or undefined when calling photosApiCompleteUploadedPhoto().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/api/photos/uploaded/{photo_id}/complete`;
        urlPath = urlPath.replace(`{${"photo_id"}}`, encodeURIComponent(String(requestParameters["photoId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            CompleteUploadedPhotoResponseSchemaFromJSON(jsonValue),
        );
    }

    /**
     * Process the uploaded photo
     * Complete Uploaded Photo
     */
    async photosApiCompleteUploadedPhoto(
        requestParameters: PhotosApiCompleteUploadedPhotoRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CompleteUploadedPhotoResponseSchema> {
        const response = await this.photosApiCompleteUploadedPhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a pending uploaded-photo record and return a presigned upload URL.
     * Create Uploaded Photo
     */
    async photosApiCreateUploadedPhotoRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateUploadedPhotoResponseSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/api/photos/create`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            CreateUploadedPhotoResponseSchemaFromJSON(jsonValue),
        );
    }

    /**
     * Create a pending uploaded-photo record and return a presigned upload URL.
     * Create Uploaded Photo
     */
    async photosApiCreateUploadedPhoto(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateUploadedPhotoResponseSchema> {
        const response = await this.photosApiCreateUploadedPhotoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Return a short-lived attachment URL for downloading a photo file.
     * Download Uploaded Photo
     */
    async photosApiDownloadUploadedPhotoRaw(
        requestParameters: PhotosApiDownloadUploadedPhotoRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["photoId"] == null) {
            throw new runtime.RequiredError(
                "photoId",
                'Required parameter "photoId" was null or undefined when calling photosApiDownloadUploadedPhoto().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/api/photos/uploaded/{photo_id}/download`;
        urlPath = urlPath.replace(`{${"photo_id"}}`, encodeURIComponent(String(requestParameters["photoId"])));

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Return a short-lived attachment URL for downloading a photo file.
     * Download Uploaded Photo
     */
    async photosApiDownloadUploadedPhoto(
        requestParameters: PhotosApiDownloadUploadedPhotoRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.photosApiDownloadUploadedPhotoRaw(requestParameters, initOverrides);
    }

    /**
     * List all uploaded photos, including those not approved.
     * List All Uploaded Photos
     */
    async photosApiListAllUploadedPhotosRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UploadedPhotoSchema>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Token"] = await this.configuration.apiKey("X-Service-Token"); // ServiceTokenAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // XSessionTokenAuth authentication
        }

        let urlPath = `/api/photos/all`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UploadedPhotoSchemaFromJSON));
    }

    /**
     * List all uploaded photos, including those not approved.
     * List All Uploaded Photos
     */
    async photosApiListAllUploadedPhotos(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UploadedPhotoSchema>> {
        const response = await this.photosApiListAllUploadedPhotosRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all uploaded photos.
     * List Uploaded Photos
     */
    async photosApiListUploadedPhotosRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UploadedPhotoSchema>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/api/photos/list`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UploadedPhotoSchemaFromJSON));
    }

    /**
     * List all uploaded photos.
     * List Uploaded Photos
     */
    async photosApiListUploadedPhotos(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UploadedPhotoSchema>> {
        const response = await this.photosApiListUploadedPhotosRaw(initOverrides);
        return await response.value();
    }
}
