# Generated by Django 5.2.4 on 2025-07-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalidea_historicaltask_historicaltasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltasklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaltasklist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltasklist',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
        migrations.DeleteModel(
            name='HistoricalTaskList',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
