# Generated by Django 5.2.4 on 2025-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalquestion_order_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='published',
            field=models.BooleanField(default=False, help_text='Indicates if the question is viewable'),
        ),
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=False, help_text='Indicates if the question is viewable'),
        ),
    ]
