# Generated by Django 5.2.4 on 2025-10-12 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historicalquestion_published_question_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_rsvp', models.BooleanField(default=False, help_text='Enable or disable RSVP functionality')),
            ],
            options={
                'verbose_name_plural': 'Wedding Settings',
            },
        ),
    ]
