# Generated by Django 5.2.4 on 2025-10-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicalrsvpformboolean_rsvpformboolean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvpformboolean',
            options={'ordering': ['order', 'question'], 'verbose_name_plural': 'RSVP Form Booleans'},
        ),
        migrations.RenameField(
            model_name='historicalrsvpformboolean',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='rsvpformboolean',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpformboolean',
            name='label',
        ),
        migrations.RemoveField(
            model_name='rsvpformboolean',
            name='label',
        ),
    ]
