# Generated by Django 5.2.4 on 2025-11-08 02:13

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_weddingsettings_wedding_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_accept_button',
            field=models.TextField(default="Lets' Do This", null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_decline_button',
            field=models.TextField(default='No Thanks', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalWeddingSettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('allow_rsvp', models.BooleanField(default=False, help_text='Enable or disable RSVP functionality')),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('rsvp_accept_button', models.TextField(default="Lets' Do This", null=True)),
                ('rsvp_decline_button', models.TextField(default='No Thanks', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical wedding settings',
                'verbose_name_plural': 'historical Wedding Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
