# Generated by Django 5.2.4 on 2025-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_historicalweddingsettings_default_data_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrsvpformboolean',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrsvpforminput',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpformboolean',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvpforminput',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
