# Generated by Django 5.2.4 on 2025-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_historicalrsvpformboolean_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_success_headline',
            field=models.TextField(default='Thank you for your RSVP!'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_success_headline',
            field=models.TextField(default='Thank you for your RSVP!'),
        ),
    ]
