# Generated by Django 5.2.4 on 2025-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_historicalweddingsettings_rsvp_success_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_accept_success_message',
            field=models.TextField(default='We look forward to celebrating with you.'),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_decline_success_message',
            field=models.TextField(default="We'll miss you at the celebration."),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_accept_success_message',
            field=models.TextField(default='We look forward to celebrating with you.'),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_decline_success_message',
            field=models.TextField(default="We'll miss you at the celebration."),
        ),
    ]
