# Generated by Django 5.2.4 on 2025-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_historicalweddingsettings_rsvp_accept_success_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='standard_group_label',
            field=models.CharField(default='Day', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='vip_group_label',
            field=models.CharField(default='Overnight', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='standard_group_label',
            field=models.CharField(default='Day', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='vip_group_label',
            field=models.CharField(default='Overnight', max_length=100),
        ),
    ]
