# Generated by Django 5.2.4 on 2025-11-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_historicalrsvpsubmission_rsvpsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpinputanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='guest_group',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpsubmission',
            name='history_user',
        ),
        migrations.AlterUniqueTogether(
            name='rsvpbooleananswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rsvpbooleananswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rsvpbooleananswer',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='rsvpinputanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rsvpinputanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rsvpinputanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='guest_group',
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpBooleanAnswer',
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpInputAnswer',
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpSubmission',
        ),
        migrations.DeleteModel(
            name='RsvpBooleanAnswer',
        ),
        migrations.DeleteModel(
            name='RsvpInputAnswer',
        ),
        migrations.DeleteModel(
            name='RsvpSubmission',
        ),
    ]
