# Generated by Django 5.2.4 on 2025-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_historicalrsvpinputanswer_history_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalweddingsettings',
            old_name='rsvp_overnight_label',
            new_name='rsvp_accommodation_label',
        ),
        migrations.RenameField(
            model_name='weddingsettings',
            old_name='rsvp_overnight_label',
            new_name='rsvp_accommodation_label',
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_vip_label',
            field=models.CharField(default="I'll join the VIP experience", max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_vip_label',
            field=models.CharField(default="I'll join the VIP experience", max_length=100),
        ),
    ]
