# Generated by Django 5.2.4 on 2025-11-15 22:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_historicalweddingsettings_rsvp_email_update_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrsvpforminput',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpforminput',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpforminput',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='historicalrsvpforminput',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rsvpformboolean',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rsvpformboolean',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='rsvpformboolean',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rsvpforminput',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rsvpforminput',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='rsvpforminput',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='HistoricalRsvpQuestion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False, help_text='Indicates if the question is viewable')),
                ('question_type', models.CharField(choices=[('text', 'Text Response'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rsvp question',
                'verbose_name_plural': 'historical RSVP Questions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RsvpQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False, help_text='Indicates if the question is viewable')),
                ('question_type', models.CharField(choices=[('text', 'Text Response'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_rsvp_question', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_rsvp_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RSVP Questions',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='RsvpQuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.rsvpquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpFormBoolean',
        ),
        migrations.DeleteModel(
            name='HistoricalRsvpFormInput',
        ),
    ]
