# Generated by Django 5.2.4 on 2025-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_historicalrsvpquestionchoice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrsvpquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Response'), ('yes_no', 'Yes/No'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rsvpquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Response'), ('yes_no', 'Yes/No'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=50),
        ),
    ]
