# Generated by Django 5.2.9 on 2025-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_historicalrsvpquestionchoice_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='show_faq',
            field=models.BooleanField(default=False, help_text='Enable or disable FAQ section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='show_faq',
            field=models.BooleanField(default=False, help_text='Enable or disable FAQ section on the site'),
        ),
    ]
