# Generated by Django 5.2.9 on 2025-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_historicalweddingsettings_rsvp_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='allow_photos',
            field=models.BooleanField(default=False, help_text='Enable or disable Photo Sharing functionality'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='allow_photos',
            field=models.BooleanField(default=False, help_text='Enable or disable Photo Sharing functionality'),
        ),
    ]
