# Generated by Django 5.2.9 on 2025-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_historicalquestion_category_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='icon',
            field=models.CharField(default='question-circle', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.CharField(default='question-circle', max_length=100),
        ),
    ]
