# Generated by Django 5.2.9 on 2025-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_historicalquestion_icon_question_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltips',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
