# Generated by Django 5.2.9 on 2025-12-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_historicalquestioncategory_historicalquestionurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalquestionurl',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questionurl',
            old_name='description',
            new_name='text',
        ),
    ]
