# Generated by Django 5.2.9 on 2025-12-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_description_historicalquestionurl_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.questioncategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_category', to='core.questioncategory'),
        ),
    ]
