# Generated by Django 5.2.9 on 2025-12-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_historicalquestion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestioncategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
