# Generated by Django 5.2.9 on 2025-12-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_historicalquestioncategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestionurl',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questionurl',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
