# Generated by Django 5.2.9 on 2025-12-29 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_historicalquestionurl_slug_questionurl_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical question', 'verbose_name_plural': 'historical FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='historicalquestioncategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical question category', 'verbose_name_plural': 'historical FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalquestionurl',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical question url', 'verbose_name_plural': 'historical FAQ Question URLs'},
        ),
        migrations.AlterModelOptions(
            name='historicaltips',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tips', 'verbose_name_plural': 'historical FAQ Tips'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question'], 'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='questionurl',
            options={'ordering': ['url'], 'verbose_name_plural': 'FAQ Question URLs'},
        ),
        migrations.AlterModelOptions(
            name='tips',
            options={'ordering': ['order'], 'verbose_name_plural': 'FAQ Tips'},
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_question_category'),
        ),
        migrations.AddConstraint(
            model_name='questionurl',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_question_url'),
        ),
    ]
