# Generated by Django 5.2.9 on 2026-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_historicalquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalquestioncategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical FAQ Category', 'verbose_name_plural': 'historical FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['order'], 'verbose_name': 'FAQ Category', 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='accommodation_group_label',
            field=models.CharField(default='Accommodation', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='accommodation_group_label',
            field=models.CharField(default='Accommodation', max_length=100),
        ),
    ]
