# Generated by Django 5.2.9 on 2026-01-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_historicalquestioncategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_accommodation_label',
            field=models.CharField(blank=True, default="I'll spend the weekend at the lodge", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_vip_label',
            field=models.CharField(blank=True, default="I'll join the VIP experience", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_accommodation_label',
            field=models.CharField(blank=True, default="I'll spend the weekend at the lodge", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_vip_label',
            field=models.CharField(blank=True, default="I'll join the VIP experience", max_length=100, null=True),
        ),
    ]
