# Generated by Django 5.2.9 on 2026-01-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_historicalweddingsettings_rsvp_accommodation_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(blank=True, default='Please let us know if you will need accommodation during the wedding weekend.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_vip_intro',
            field=models.TextField(blank=True, default='Please let us know if you will be joining us for the VIP overnight experience.', null=True),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_accommodation_intro',
            field=models.TextField(blank=True, default='Please let us know if you will need accommodation during the wedding weekend.', null=True),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_vip_intro',
            field=models.TextField(blank=True, default='Please let us know if you will be joining us for the VIP overnight experience.', null=True),
        ),
    ]
