# Generated by Django 5.2.9 on 2026-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_historicalweddingsettings_rsvp_accommodation_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='rsvp_email_update_label',
            field=models.CharField(blank=True, default='Yes, keep me updated via email', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='rsvp_email_update_label',
            field=models.CharField(blank=True, default='Yes, keep me updated via email', max_length=150, null=True),
        ),
    ]
