# Generated by Django 5.2.10 on 2026-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_historicalweddingsettings_rsvp_email_update_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='show_venue',
            field=models.BooleanField(default=False, help_text='Enable or disable Venue section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='show_venue',
            field=models.BooleanField(default=False, help_text='Enable or disable Venue section on the site'),
        ),
    ]
