# Generated by Django 5.2.10 on 2026-01-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_historicalweddingsettings_show_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_page_description',
            field=models.TextField(default="Discover the beautiful location where we'll be celebrating our special day."),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_page_title',
            field=models.CharField(default='Our Venue', max_length=150),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_page_description',
            field=models.TextField(default="Discover the beautiful location where we'll be celebrating our special day."),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_page_title',
            field=models.CharField(default='Our Venue', max_length=150),
        ),
    ]
