# Generated by Django 5.2.10 on 2026-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_historicalweddingsettings_venue_page_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_address_line_one',
            field=models.CharField(default='1234 Wedding Lane', max_length=250),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_address_line_two',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_city',
            field=models.CharField(default='Hocking Hills', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_name',
            field=models.CharField(default='Timberframe Lodge', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_parking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_state',
            field=models.CharField(default='Ohio', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_zipcode',
            field=models.CharField(default='43119', max_length=20),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_address_line_one',
            field=models.CharField(default='1234 Wedding Lane', max_length=250),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_address_line_two',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_city',
            field=models.CharField(default='Hocking Hills', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_name',
            field=models.CharField(default='Timberframe Lodge', max_length=150),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_parking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_state',
            field=models.CharField(default='Ohio', max_length=100),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_zipcode',
            field=models.CharField(default='43119', max_length=20),
        ),
    ]
