# Generated by Django 5.2.10 on 2026-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_historicalweddingsettings_venue_address_line_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_gallery_description',
            field=models.TextField(default='We’re really excited to celebrate with you - take a look at our venue while we wait for the big day!'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='venue_gallery_title',
            field=models.CharField(default='Check Out Our Venue', max_length=150),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_gallery_description',
            field=models.TextField(default='We’re really excited to celebrate with you - take a look at our venue while we wait for the big day!'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='venue_gallery_title',
            field=models.CharField(default='Check Out Our Venue', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='venue_name',
            field=models.CharField(default='The Lodge', max_length=150),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='venue_name',
            field=models.CharField(default='The Lodge', max_length=150),
        ),
    ]
