# Generated by Django 5.2.11 on 2026-02-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_historicalweddingsettings_venue_gallery_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['order', 'start'], 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AddField(
            model_name='historicaltimeline',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for timeline events'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for timeline events'),
        ),
    ]
