# Generated by Django 5.2.11 on 2026-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_historicalaccommodation_accommodation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Accommodations'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for accommodations'),
        ),
        migrations.AddField(
            model_name='historicalaccommodation',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for accommodations'),
        ),
    ]
