# Generated by Django 5.2.11 on 2026-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_accommodation_options_accommodation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_default_url',
            field=models.URLField(default='https://dev.internal/rsvp', help_text='Default URL for RSVP page if not using personalized URLs', max_length=500),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_default_url',
            field=models.URLField(default='https://dev.internal/rsvp', help_text='Default URL for RSVP page if not using personalized URLs', max_length=500),
        ),
    ]
