# Generated by Django 5.2.11 on 2026-02-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('core', '0062_historicalweddingsettings_rsvp_default_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_qr_code',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='QR code for RSVP start page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code for RSVP start page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code_wedding_settings', to='attachments.attachment'),
        ),
    ]
