# Generated by Django 5.2.11 on 2026-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_historicalweddingsettings_rsvp_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='rsvp_qr_code_url',
            field=models.URLField(blank=True, help_text='URL for RSVP start page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='rsvp_qr_code_url',
            field=models.URLField(blank=True, help_text='URL for RSVP start page', max_length=500, null=True),
        ),
    ]
