# Generated by Django 6.0.3 on 2026-04-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_historicalweddingsettings_rsvp_qr_code_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalweddingsettings',
            name='rsvp_qr_code_url',
        ),
        migrations.RemoveField(
            model_name='weddingsettings',
            name='rsvp_qr_code_url',
        ),
    ]
