# Generated by Django 6.0.6 on 2026-07-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_historicalweddingsettings_rsvp_qr_code_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='enable_faq',
            field=models.BooleanField(default=True, help_text='Enable or disable FAQ section on the site'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='enable_our_story',
            field=models.BooleanField(default=True, help_text='Enable or disable Our Story section on the site'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='enable_rsvp',
            field=models.BooleanField(default=True, help_text='Enable or disable RSVP section on the site'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='enable_upload_photos',
            field=models.BooleanField(default=True, help_text='Enable or disable Upload Photos section on the site'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='enable_venue',
            field=models.BooleanField(default=True, help_text='Enable or disable Venue section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='enable_faq',
            field=models.BooleanField(default=True, help_text='Enable or disable FAQ section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='enable_our_story',
            field=models.BooleanField(default=True, help_text='Enable or disable Our Story section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='enable_rsvp',
            field=models.BooleanField(default=True, help_text='Enable or disable RSVP section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='enable_upload_photos',
            field=models.BooleanField(default=True, help_text='Enable or disable Upload Photos section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='enable_venue',
            field=models.BooleanField(default=True, help_text='Enable or disable Venue section on the site'),
        ),
    ]
