# Generated by Django 6.0.6 on 2026-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_historicalweddingsettings_enable_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='show_our_story',
            field=models.BooleanField(default=True, help_text='Enable or disable Our Story section on the site'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='show_our_story',
            field=models.BooleanField(default=True, help_text='Enable or disable Our Story section on the site'),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Enable or disable FAQ section on the site'),
        ),
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='show_venue',
            field=models.BooleanField(default=True, help_text='Enable or disable Venue section on the site'),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Enable or disable FAQ section on the site'),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='show_venue',
            field=models.BooleanField(default=True, help_text='Enable or disable Venue section on the site'),
        ),
    ]
