# Generated by Django 6.0.8 on 2026-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_historicalweddingsettings_show_our_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='require_photo_approval',
            field=models.BooleanField(default=False, help_text='Require admin approval for uploaded photos before they are visible'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='require_photo_approval',
            field=models.BooleanField(default=False, help_text='Require admin approval for uploaded photos before they are visible'),
        ),
    ]
