# Generated by Django 6.0.8 on 2026-08-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('core', '0068_historicalweddingsettings_require_photo_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='photo_qr_code',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='QR code for photo upload page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='historicalweddingsettings',
            name='photo_upload_url',
            field=models.URLField(default='https://dev.internal/photos/upload/', help_text='Default URL for photo upload page', max_length=500),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='photo_qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code for photo upload page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code_photo_upload', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='weddingsettings',
            name='photo_upload_url',
            field=models.URLField(default='https://dev.internal/photos/upload/', help_text='Default URL for photo upload page', max_length=500),
        ),
    ]
