# Generated by Django 6.0.8 on 2026-08-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_historicalweddingsettings_photo_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweddingsettings',
            name='photo_upload_url',
            field=models.URLField(default='https://dev.internal/photos', help_text='Default URL for photo upload page', max_length=500),
        ),
        migrations.AlterField(
            model_name='weddingsettings',
            name='photo_upload_url',
            field=models.URLField(default='https://dev.internal/photos', help_text='Default URL for photo upload page', max_length=500),
        ),
    ]
