http:
  routers:
    django-local:
      rule: "Host(`dev.internal`)"
      entryPoints:
        - websecure
      service: django-local-service
      priority: 100
      tls: {}

    django-local-http:
      rule: "Host(`dev.internal`)"
      entryPoints:
        - web
      service: django-local-service
      priority: 100

  services:
    django-local-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"
        passHostHeader: true
