/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AccommodationSchema
 */
export interface AccommodationSchema {
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    url?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    phoneNumber?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    addressLineOne?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    addressLineTwo?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    city?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    state?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    zipcode?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationSchema
     */
    accommodationType: string;
    /**
     *
     * @type {number}
     * @memberof AccommodationSchema
     */
    order: number;
    /**
     *
     * @type {Date}
     * @memberof AccommodationSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AccommodationSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AccommodationSchema interface.
 */
export function instanceOfAccommodationSchema(value: object): value is AccommodationSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("accommodationType" in value) || value["accommodationType"] === undefined) return false;
    if (!("order" in value) || value["order"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function AccommodationSchemaFromJSON(json: any): AccommodationSchema {
    return AccommodationSchemaFromJSONTyped(json, false);
}

export function AccommodationSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        url: json["url"] == null ? undefined : json["url"],
        phoneNumber: json["phone_number"] == null ? undefined : json["phone_number"],
        addressLineOne: json["address_line_one"] == null ? undefined : json["address_line_one"],
        addressLineTwo: json["address_line_two"] == null ? undefined : json["address_line_two"],
        city: json["city"] == null ? undefined : json["city"],
        state: json["state"] == null ? undefined : json["state"],
        zipcode: json["zipcode"] == null ? undefined : json["zipcode"],
        accommodationType: json["accommodation_type"],
        order: json["order"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function AccommodationSchemaToJSON(json: any): AccommodationSchema {
    return AccommodationSchemaToJSONTyped(json, false);
}

export function AccommodationSchemaToJSONTyped(
    value?: AccommodationSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        url: value["url"],
        phone_number: value["phoneNumber"],
        address_line_one: value["addressLineOne"],
        address_line_two: value["addressLineTwo"],
        city: value["city"],
        state: value["state"],
        zipcode: value["zipcode"],
        accommodation_type: value["accommodationType"],
        order: value["order"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
