/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AccommodationCreateSchema
 */
export interface AccommodationCreateSchema {
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    url?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    phoneNumber?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    addressLineOne?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    addressLineTwo?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    city?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    state?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    zipcode?: string | null;
    /**
     *
     * @type {string}
     * @memberof AccommodationCreateSchema
     */
    accommodationType?: string | null;
    /**
     *
     * @type {number}
     * @memberof AccommodationCreateSchema
     */
    order?: number | null;
}

/**
 * Check if a given object implements the AccommodationCreateSchema interface.
 */
export function instanceOfAccommodationCreateSchema(value: object): value is AccommodationCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function AccommodationCreateSchemaFromJSON(json: any): AccommodationCreateSchema {
    return AccommodationCreateSchemaFromJSONTyped(json, false);
}

export function AccommodationCreateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AccommodationCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"] == null ? undefined : json["description"],
        url: json["url"] == null ? undefined : json["url"],
        phoneNumber: json["phone_number"] == null ? undefined : json["phone_number"],
        addressLineOne: json["address_line_one"] == null ? undefined : json["address_line_one"],
        addressLineTwo: json["address_line_two"] == null ? undefined : json["address_line_two"],
        city: json["city"] == null ? undefined : json["city"],
        state: json["state"] == null ? undefined : json["state"],
        zipcode: json["zipcode"] == null ? undefined : json["zipcode"],
        accommodationType: json["accommodation_type"] == null ? undefined : json["accommodation_type"],
        order: json["order"] == null ? undefined : json["order"],
    };
}

export function AccommodationCreateSchemaToJSON(json: any): AccommodationCreateSchema {
    return AccommodationCreateSchemaToJSONTyped(json, false);
}

export function AccommodationCreateSchemaToJSONTyped(
    value?: AccommodationCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
        url: value["url"],
        phone_number: value["phoneNumber"],
        address_line_one: value["addressLineOne"],
        address_line_two: value["addressLineTwo"],
        city: value["city"],
        state: value["state"],
        zipcode: value["zipcode"],
        accommodation_type: value["accommodationType"],
        order: value["order"],
    };
}
