/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AdditionalPrice
 */
export interface AdditionalPrice {}

/**
 * Check if a given object implements the AdditionalPrice interface.
 */
export function instanceOfAdditionalPrice(value: object): value is AdditionalPrice {
    return true;
}

export function AdditionalPriceFromJSON(json: any): AdditionalPrice {
    return AdditionalPriceFromJSONTyped(json, false);
}

export function AdditionalPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalPrice {
    return json;
}

export function AdditionalPriceToJSON(json: any): AdditionalPrice {
    return AdditionalPriceToJSONTyped(json, false);
}

export function AdditionalPriceToJSONTyped(value?: AdditionalPrice | null, ignoreDiscriminator: boolean = false): any {
    return value;
}
