/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AttachmentUpdateSchema
 */
export interface AttachmentUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof AttachmentUpdateSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentUpdateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AttachmentUpdateSchema interface.
 */
export function instanceOfAttachmentUpdateSchema(value: object): value is AttachmentUpdateSchema {
    return true;
}

export function AttachmentUpdateSchemaFromJSON(json: any): AttachmentUpdateSchema {
    return AttachmentUpdateSchemaFromJSONTyped(json, false);
}

export function AttachmentUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function AttachmentUpdateSchemaToJSON(json: any): AttachmentUpdateSchema {
    return AttachmentUpdateSchemaToJSONTyped(json, false);
}

export function AttachmentUpdateSchemaToJSONTyped(
    value?: AttachmentUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
    };
}
