/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AttachmentSchema
 */
export interface AttachmentSchema {
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    slug?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    filename: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    fileUrl: string;
    /**
     *
     * @type {number}
     * @memberof AttachmentSchema
     */
    contentTypeId: number;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    contentTypeAppLabel: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    contentTypeModel: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    objectId: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    uploadedById?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    uploadedByName?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    updatedById?: string | null;
    /**
     *
     * @type {string}
     * @memberof AttachmentSchema
     */
    updatedByName?: string | null;
    /**
     *
     * @type {Date}
     * @memberof AttachmentSchema
     */
    uploadedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AttachmentSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AttachmentSchema interface.
 */
export function instanceOfAttachmentSchema(value: object): value is AttachmentSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("filename" in value) || value["filename"] === undefined) return false;
    if (!("fileUrl" in value) || value["fileUrl"] === undefined) return false;
    if (!("contentTypeId" in value) || value["contentTypeId"] === undefined) return false;
    if (!("contentTypeAppLabel" in value) || value["contentTypeAppLabel"] === undefined) return false;
    if (!("contentTypeModel" in value) || value["contentTypeModel"] === undefined) return false;
    if (!("objectId" in value) || value["objectId"] === undefined) return false;
    if (!("uploadedAt" in value) || value["uploadedAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function AttachmentSchemaFromJSON(json: any): AttachmentSchema {
    return AttachmentSchemaFromJSONTyped(json, false);
}

export function AttachmentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"] == null ? undefined : json["name"],
        slug: json["slug"] == null ? undefined : json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        filename: json["filename"],
        fileUrl: json["file_url"],
        contentTypeId: json["content_type_id"],
        contentTypeAppLabel: json["content_type_app_label"],
        contentTypeModel: json["content_type_model"],
        objectId: json["object_id"],
        uploadedById: json["uploaded_by_id"] == null ? undefined : json["uploaded_by_id"],
        uploadedByName: json["uploaded_by_name"] == null ? undefined : json["uploaded_by_name"],
        updatedById: json["updated_by_id"] == null ? undefined : json["updated_by_id"],
        updatedByName: json["updated_by_name"] == null ? undefined : json["updated_by_name"],
        uploadedAt: new Date(json["uploaded_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function AttachmentSchemaToJSON(json: any): AttachmentSchema {
    return AttachmentSchemaToJSONTyped(json, false);
}

export function AttachmentSchemaToJSONTyped(
    value?: AttachmentSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        filename: value["filename"],
        file_url: value["fileUrl"],
        content_type_id: value["contentTypeId"],
        content_type_app_label: value["contentTypeAppLabel"],
        content_type_model: value["contentTypeModel"],
        object_id: value["objectId"],
        uploaded_by_id: value["uploadedById"],
        uploaded_by_name: value["uploadedByName"],
        updated_by_id: value["updatedById"],
        updated_by_name: value["updatedByName"],
        uploaded_at: value["uploadedAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
