/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { QuestionSchema } from "./QuestionSchema";
import {
    QuestionSchemaFromJSON,
    QuestionSchemaFromJSONTyped,
    QuestionSchemaToJSON,
    QuestionSchemaToJSONTyped,
} from "./QuestionSchema";
import type { TipsSchema } from "./TipsSchema";
import { TipsSchemaFromJSON, TipsSchemaFromJSONTyped, TipsSchemaToJSON, TipsSchemaToJSONTyped } from "./TipsSchema";

/**
 *
 * @export
 * @interface CategoryContentSchema
 */
export interface CategoryContentSchema {
    /**
     *
     * @type {string}
     * @memberof CategoryContentSchema
     */
    categoryId: string;
    /**
     *
     * @type {string}
     * @memberof CategoryContentSchema
     */
    categoryName: string;
    /**
     *
     * @type {number}
     * @memberof CategoryContentSchema
     */
    categoryOrder: number;
    /**
     *
     * @type {Array<QuestionSchema>}
     * @memberof CategoryContentSchema
     */
    questions: Array<QuestionSchema>;
    /**
     *
     * @type {Array<TipsSchema>}
     * @memberof CategoryContentSchema
     */
    tips: Array<TipsSchema>;
}

/**
 * Check if a given object implements the CategoryContentSchema interface.
 */
export function instanceOfCategoryContentSchema(value: object): value is CategoryContentSchema {
    if (!("categoryId" in value) || value["categoryId"] === undefined) return false;
    if (!("categoryName" in value) || value["categoryName"] === undefined) return false;
    if (!("categoryOrder" in value) || value["categoryOrder"] === undefined) return false;
    if (!("questions" in value) || value["questions"] === undefined) return false;
    if (!("tips" in value) || value["tips"] === undefined) return false;
    return true;
}

export function CategoryContentSchemaFromJSON(json: any): CategoryContentSchema {
    return CategoryContentSchemaFromJSONTyped(json, false);
}

export function CategoryContentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryContentSchema {
    if (json == null) {
        return json;
    }
    return {
        categoryId: json["category_id"],
        categoryName: json["category_name"],
        categoryOrder: json["category_order"],
        questions: (json["questions"] as Array<any>).map(QuestionSchemaFromJSON),
        tips: (json["tips"] as Array<any>).map(TipsSchemaFromJSON),
    };
}

export function CategoryContentSchemaToJSON(json: any): CategoryContentSchema {
    return CategoryContentSchemaToJSONTyped(json, false);
}

export function CategoryContentSchemaToJSONTyped(
    value?: CategoryContentSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        category_id: value["categoryId"],
        category_name: value["categoryName"],
        category_order: value["categoryOrder"],
        questions: (value["questions"] as Array<any>).map(QuestionSchemaToJSON),
        tips: (value["tips"] as Array<any>).map(TipsSchemaToJSON),
    };
}
