/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CategoryCreateSchema
 */
export interface CategoryCreateSchema {
    /**
     *
     * @type {string}
     * @memberof CategoryCreateSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CategoryCreateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CategoryCreateSchema interface.
 */
export function instanceOfCategoryCreateSchema(value: object): value is CategoryCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function CategoryCreateSchemaFromJSON(json: any): CategoryCreateSchema {
    return CategoryCreateSchemaFromJSONTyped(json, false);
}

export function CategoryCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function CategoryCreateSchemaToJSON(json: any): CategoryCreateSchema {
    return CategoryCreateSchemaToJSONTyped(json, false);
}

export function CategoryCreateSchemaToJSONTyped(
    value?: CategoryCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
    };
}
