/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CategorySchema
 */
export interface CategorySchema {
    /**
     *
     * @type {string}
     * @memberof CategorySchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof CategorySchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CategorySchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof CategorySchema
     */
    description?: string | null;
    /**
     *
     * @type {Date}
     * @memberof CategorySchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof CategorySchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the CategorySchema interface.
 */
export function instanceOfCategorySchema(value: object): value is CategorySchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function CategorySchemaFromJSON(json: any): CategorySchema {
    return CategorySchemaFromJSONTyped(json, false);
}

export function CategorySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function CategorySchemaToJSON(json: any): CategorySchema {
    return CategorySchemaToJSONTyped(json, false);
}

export function CategorySchemaToJSONTyped(value?: CategorySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
