/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CategoryUpdateSchema
 */
export interface CategoryUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof CategoryUpdateSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof CategoryUpdateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CategoryUpdateSchema interface.
 */
export function instanceOfCategoryUpdateSchema(value: object): value is CategoryUpdateSchema {
    return true;
}

export function CategoryUpdateSchemaFromJSON(json: any): CategoryUpdateSchema {
    return CategoryUpdateSchemaFromJSONTyped(json, false);
}

export function CategoryUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function CategoryUpdateSchemaToJSON(json: any): CategoryUpdateSchema {
    return CategoryUpdateSchemaToJSONTyped(json, false);
}

export function CategoryUpdateSchemaToJSONTyped(
    value?: CategoryUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
    };
}
