/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ContactSchema
 */
export interface ContactSchema {
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    slug?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    company?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    email?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    phone?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    website?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    category?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    notes?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    createdById?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    createdByName?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    updatedById?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactSchema
     */
    updatedByName?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ContactSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ContactSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ContactSchema interface.
 */
export function instanceOfContactSchema(value: object): value is ContactSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function ContactSchemaFromJSON(json: any): ContactSchema {
    return ContactSchemaFromJSONTyped(json, false);
}

export function ContactSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"] == null ? undefined : json["name"],
        slug: json["slug"] == null ? undefined : json["slug"],
        company: json["company"] == null ? undefined : json["company"],
        email: json["email"] == null ? undefined : json["email"],
        phone: json["phone"] == null ? undefined : json["phone"],
        website: json["website"] == null ? undefined : json["website"],
        category: json["category"] == null ? undefined : json["category"],
        notes: json["notes"] == null ? undefined : json["notes"],
        createdById: json["created_by_id"] == null ? undefined : json["created_by_id"],
        createdByName: json["created_by_name"] == null ? undefined : json["created_by_name"],
        updatedById: json["updated_by_id"] == null ? undefined : json["updated_by_id"],
        updatedByName: json["updated_by_name"] == null ? undefined : json["updated_by_name"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function ContactSchemaToJSON(json: any): ContactSchema {
    return ContactSchemaToJSONTyped(json, false);
}

export function ContactSchemaToJSONTyped(value?: ContactSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        company: value["company"],
        email: value["email"],
        phone: value["phone"],
        website: value["website"],
        category: value["category"],
        notes: value["notes"],
        created_by_id: value["createdById"],
        created_by_name: value["createdByName"],
        updated_by_id: value["updatedById"],
        updated_by_name: value["updatedByName"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
