/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ContactFilterSchema
 */
export interface ContactFilterSchema {
    /**
     *
     * @type {string}
     * @memberof ContactFilterSchema
     */
    category?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactFilterSchema
     */
    search?: string | null;
}

/**
 * Check if a given object implements the ContactFilterSchema interface.
 */
export function instanceOfContactFilterSchema(value: object): value is ContactFilterSchema {
    return true;
}

export function ContactFilterSchemaFromJSON(json: any): ContactFilterSchema {
    return ContactFilterSchemaFromJSONTyped(json, false);
}

export function ContactFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        category: json["category"] == null ? undefined : json["category"],
        search: json["search"] == null ? undefined : json["search"],
    };
}

export function ContactFilterSchemaToJSON(json: any): ContactFilterSchema {
    return ContactFilterSchemaToJSONTyped(json, false);
}

export function ContactFilterSchemaToJSONTyped(
    value?: ContactFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        category: value["category"],
        search: value["search"],
    };
}
