/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ContentTypeSchema
 */
export interface ContentTypeSchema {
    /**
     *
     * @type {number}
     * @memberof ContentTypeSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof ContentTypeSchema
     */
    appLabel: string;
    /**
     *
     * @type {string}
     * @memberof ContentTypeSchema
     */
    model: string;
}

/**
 * Check if a given object implements the ContentTypeSchema interface.
 */
export function instanceOfContentTypeSchema(value: object): value is ContentTypeSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("appLabel" in value) || value["appLabel"] === undefined) return false;
    if (!("model" in value) || value["model"] === undefined) return false;
    return true;
}

export function ContentTypeSchemaFromJSON(json: any): ContentTypeSchema {
    return ContentTypeSchemaFromJSONTyped(json, false);
}

export function ContentTypeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentTypeSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        appLabel: json["app_label"],
        model: json["model"],
    };
}

export function ContentTypeSchemaToJSON(json: any): ContentTypeSchema {
    return ContentTypeSchemaToJSONTyped(json, false);
}

export function ContentTypeSchemaToJSONTyped(
    value?: ContentTypeSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        app_label: value["appLabel"],
        model: value["model"],
    };
}
