/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ContactUpdateSchema
 */
export interface ContactUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    company?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    email?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    phone?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    website?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    category?: string | null;
    /**
     *
     * @type {string}
     * @memberof ContactUpdateSchema
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the ContactUpdateSchema interface.
 */
export function instanceOfContactUpdateSchema(value: object): value is ContactUpdateSchema {
    return true;
}

export function ContactUpdateSchemaFromJSON(json: any): ContactUpdateSchema {
    return ContactUpdateSchemaFromJSONTyped(json, false);
}

export function ContactUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        company: json["company"] == null ? undefined : json["company"],
        email: json["email"] == null ? undefined : json["email"],
        phone: json["phone"] == null ? undefined : json["phone"],
        website: json["website"] == null ? undefined : json["website"],
        category: json["category"] == null ? undefined : json["category"],
        notes: json["notes"] == null ? undefined : json["notes"],
    };
}

export function ContactUpdateSchemaToJSON(json: any): ContactUpdateSchema {
    return ContactUpdateSchemaToJSONTyped(json, false);
}

export function ContactUpdateSchemaToJSONTyped(
    value?: ContactUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        company: value["company"],
        email: value["email"],
        phone: value["phone"],
        website: value["website"],
        category: value["category"],
        notes: value["notes"],
    };
}
