/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateUploadedPhotoResponseSchema
 */
export interface CreateUploadedPhotoResponseSchema {
    /**
     *
     * @type {string}
     * @memberof CreateUploadedPhotoResponseSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof CreateUploadedPhotoResponseSchema
     */
    uploadUrl: string;
}

/**
 * Check if a given object implements the CreateUploadedPhotoResponseSchema interface.
 */
export function instanceOfCreateUploadedPhotoResponseSchema(value: object): value is CreateUploadedPhotoResponseSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("uploadUrl" in value) || value["uploadUrl"] === undefined) return false;
    return true;
}

export function CreateUploadedPhotoResponseSchemaFromJSON(json: any): CreateUploadedPhotoResponseSchema {
    return CreateUploadedPhotoResponseSchemaFromJSONTyped(json, false);
}

export function CreateUploadedPhotoResponseSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CreateUploadedPhotoResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        uploadUrl: json["upload_url"],
    };
}

export function CreateUploadedPhotoResponseSchemaToJSON(json: any): CreateUploadedPhotoResponseSchema {
    return CreateUploadedPhotoResponseSchemaToJSONTyped(json, false);
}

export function CreateUploadedPhotoResponseSchemaToJSONTyped(
    value?: CreateUploadedPhotoResponseSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        upload_url: value["uploadUrl"],
    };
}
