/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DeadlineListCreateSchema
 */
export interface DeadlineListCreateSchema {
    /**
     *
     * @type {string}
     * @memberof DeadlineListCreateSchema
     */
    name: string;
}

/**
 * Check if a given object implements the DeadlineListCreateSchema interface.
 */
export function instanceOfDeadlineListCreateSchema(value: object): value is DeadlineListCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function DeadlineListCreateSchemaFromJSON(json: any): DeadlineListCreateSchema {
    return DeadlineListCreateSchemaFromJSONTyped(json, false);
}

export function DeadlineListCreateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DeadlineListCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
    };
}

export function DeadlineListCreateSchemaToJSON(json: any): DeadlineListCreateSchema {
    return DeadlineListCreateSchemaToJSONTyped(json, false);
}

export function DeadlineListCreateSchemaToJSONTyped(
    value?: DeadlineListCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
