/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DeadlineFilterSchema
 */
export interface DeadlineFilterSchema {
    /**
     *
     * @type {string}
     * @memberof DeadlineFilterSchema
     */
    deadlineListId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DeadlineFilterSchema
     */
    completed?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineFilterSchema
     */
    assignedToId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DeadlineFilterSchema
     */
    overdue?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineFilterSchema
     */
    search?: string | null;
}

/**
 * Check if a given object implements the DeadlineFilterSchema interface.
 */
export function instanceOfDeadlineFilterSchema(value: object): value is DeadlineFilterSchema {
    return true;
}

export function DeadlineFilterSchemaFromJSON(json: any): DeadlineFilterSchema {
    return DeadlineFilterSchemaFromJSONTyped(json, false);
}

export function DeadlineFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadlineFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        deadlineListId: json["deadline_list_id"] == null ? undefined : json["deadline_list_id"],
        completed: json["completed"] == null ? undefined : json["completed"],
        assignedToId: json["assigned_to_id"] == null ? undefined : json["assigned_to_id"],
        overdue: json["overdue"] == null ? undefined : json["overdue"],
        search: json["search"] == null ? undefined : json["search"],
    };
}

export function DeadlineFilterSchemaToJSON(json: any): DeadlineFilterSchema {
    return DeadlineFilterSchemaToJSONTyped(json, false);
}

export function DeadlineFilterSchemaToJSONTyped(
    value?: DeadlineFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        deadline_list_id: value["deadlineListId"],
        completed: value["completed"],
        assigned_to_id: value["assignedToId"],
        overdue: value["overdue"],
        search: value["search"],
    };
}
