/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DeadlineUpdateSchema
 */
export interface DeadlineUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof DeadlineUpdateSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineUpdateSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineUpdateSchema
     */
    deadlineListId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof DeadlineUpdateSchema
     */
    dueDate?: Date | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineUpdateSchema
     */
    assignedToId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DeadlineUpdateSchema
     */
    completed?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineUpdateSchema
     */
    completedNote?: string | null;
}

/**
 * Check if a given object implements the DeadlineUpdateSchema interface.
 */
export function instanceOfDeadlineUpdateSchema(value: object): value is DeadlineUpdateSchema {
    return true;
}

export function DeadlineUpdateSchemaFromJSON(json: any): DeadlineUpdateSchema {
    return DeadlineUpdateSchemaFromJSONTyped(json, false);
}

export function DeadlineUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadlineUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        description: json["description"] == null ? undefined : json["description"],
        deadlineListId: json["deadline_list_id"] == null ? undefined : json["deadline_list_id"],
        dueDate: json["due_date"] == null ? undefined : new Date(json["due_date"]),
        assignedToId: json["assigned_to_id"] == null ? undefined : json["assigned_to_id"],
        completed: json["completed"] == null ? undefined : json["completed"],
        completedNote: json["completed_note"] == null ? undefined : json["completed_note"],
    };
}

export function DeadlineUpdateSchemaToJSON(json: any): DeadlineUpdateSchema {
    return DeadlineUpdateSchemaToJSONTyped(json, false);
}

export function DeadlineUpdateSchemaToJSONTyped(
    value?: DeadlineUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
        deadline_list_id: value["deadlineListId"],
        due_date: value["dueDate"] == null ? value["dueDate"] : value["dueDate"].toISOString().substring(0, 10),
        assigned_to_id: value["assignedToId"],
        completed: value["completed"],
        completed_note: value["completedNote"],
    };
}
