/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DeadlineCreateSchema
 */
export interface DeadlineCreateSchema {
    /**
     *
     * @type {string}
     * @memberof DeadlineCreateSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof DeadlineCreateSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineCreateSchema
     */
    deadlineListId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof DeadlineCreateSchema
     */
    dueDate?: Date | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineCreateSchema
     */
    assignedToId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof DeadlineCreateSchema
     */
    completed?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof DeadlineCreateSchema
     */
    completedNote?: string | null;
}

/**
 * Check if a given object implements the DeadlineCreateSchema interface.
 */
export function instanceOfDeadlineCreateSchema(value: object): value is DeadlineCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function DeadlineCreateSchemaFromJSON(json: any): DeadlineCreateSchema {
    return DeadlineCreateSchemaFromJSONTyped(json, false);
}

export function DeadlineCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadlineCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"] == null ? undefined : json["description"],
        deadlineListId: json["deadline_list_id"] == null ? undefined : json["deadline_list_id"],
        dueDate: json["due_date"] == null ? undefined : new Date(json["due_date"]),
        assignedToId: json["assigned_to_id"] == null ? undefined : json["assigned_to_id"],
        completed: json["completed"] == null ? undefined : json["completed"],
        completedNote: json["completed_note"] == null ? undefined : json["completed_note"],
    };
}

export function DeadlineCreateSchemaToJSON(json: any): DeadlineCreateSchema {
    return DeadlineCreateSchemaToJSONTyped(json, false);
}

export function DeadlineCreateSchemaToJSONTyped(
    value?: DeadlineCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
        deadline_list_id: value["deadlineListId"],
        due_date: value["dueDate"] == null ? value["dueDate"] : value["dueDate"].toISOString().substring(0, 10),
        assigned_to_id: value["assignedToId"],
        completed: value["completed"],
        completed_note: value["completedNote"],
    };
}
