/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DeleteImageResponseSchema
 */
export interface DeleteImageResponseSchema {
    /**
     *
     * @type {boolean}
     * @memberof DeleteImageResponseSchema
     */
    success: boolean;
    /**
     *
     * @type {string}
     * @memberof DeleteImageResponseSchema
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteImageResponseSchema interface.
 */
export function instanceOfDeleteImageResponseSchema(value: object): value is DeleteImageResponseSchema {
    if (!("success" in value) || value["success"] === undefined) return false;
    if (!("message" in value) || value["message"] === undefined) return false;
    return true;
}

export function DeleteImageResponseSchemaFromJSON(json: any): DeleteImageResponseSchema {
    return DeleteImageResponseSchemaFromJSONTyped(json, false);
}

export function DeleteImageResponseSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DeleteImageResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        success: json["success"],
        message: json["message"],
    };
}

export function DeleteImageResponseSchemaToJSON(json: any): DeleteImageResponseSchema {
    return DeleteImageResponseSchemaToJSONTyped(json, false);
}

export function DeleteImageResponseSchemaToJSONTyped(
    value?: DeleteImageResponseSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        success: value["success"],
        message: value["message"],
    };
}
