/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface EmailTaskSchema
 */
export interface EmailTaskSchema {
    /**
     *
     * @type {boolean}
     * @memberof EmailTaskSchema
     */
    success: boolean;
    /**
     *
     * @type {string}
     * @memberof EmailTaskSchema
     */
    message: string;
    /**
     *
     * @type {string}
     * @memberof EmailTaskSchema
     */
    taskId: string;
}

/**
 * Check if a given object implements the EmailTaskSchema interface.
 */
export function instanceOfEmailTaskSchema(value: object): value is EmailTaskSchema {
    if (!("success" in value) || value["success"] === undefined) return false;
    if (!("message" in value) || value["message"] === undefined) return false;
    if (!("taskId" in value) || value["taskId"] === undefined) return false;
    return true;
}

export function EmailTaskSchemaFromJSON(json: any): EmailTaskSchema {
    return EmailTaskSchemaFromJSONTyped(json, false);
}

export function EmailTaskSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTaskSchema {
    if (json == null) {
        return json;
    }
    return {
        success: json["success"],
        message: json["message"],
        taskId: json["task_id"],
    };
}

export function EmailTaskSchemaToJSON(json: any): EmailTaskSchema {
    return EmailTaskSchemaToJSONTyped(json, false);
}

export function EmailTaskSchemaToJSONTyped(value?: EmailTaskSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        success: value["success"],
        message: value["message"],
        task_id: value["taskId"],
    };
}
