/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ActualAmount } from "./ActualAmount";
import {
    ActualAmountFromJSON,
    ActualAmountFromJSONTyped,
    ActualAmountToJSON,
    ActualAmountToJSONTyped,
} from "./ActualAmount";
import type { AdditionalPrice1 } from "./AdditionalPrice1";
import {
    AdditionalPrice1FromJSON,
    AdditionalPrice1FromJSONTyped,
    AdditionalPrice1ToJSON,
    AdditionalPrice1ToJSONTyped,
} from "./AdditionalPrice1";
import type { EstimatedAmount } from "./EstimatedAmount";
import {
    EstimatedAmountFromJSON,
    EstimatedAmountFromJSONTyped,
    EstimatedAmountToJSON,
    EstimatedAmountToJSONTyped,
} from "./EstimatedAmount";
import type { UnitPrice1 } from "./UnitPrice1";
import { UnitPrice1FromJSON, UnitPrice1FromJSONTyped, UnitPrice1ToJSON, UnitPrice1ToJSONTyped } from "./UnitPrice1";

/**
 *
 * @export
 * @interface ExpenseUpdateSchema
 */
export interface ExpenseUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof ExpenseUpdateSchema
     */
    item?: string | null;
    /**
     *
     * @type {string}
     * @memberof ExpenseUpdateSchema
     */
    description?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ExpenseUpdateSchema
     */
    date?: Date | null;
    /**
     *
     * @type {string}
     * @memberof ExpenseUpdateSchema
     */
    categoryId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ExpenseUpdateSchema
     */
    vendorId?: string | null;
    /**
     *
     * @type {number}
     * @memberof ExpenseUpdateSchema
     */
    quantity?: number | null;
    /**
     *
     * @type {UnitPrice1}
     * @memberof ExpenseUpdateSchema
     */
    unitPrice?: UnitPrice1 | null;
    /**
     *
     * @type {AdditionalPrice1}
     * @memberof ExpenseUpdateSchema
     */
    additionalPrice?: AdditionalPrice1 | null;
    /**
     *
     * @type {EstimatedAmount}
     * @memberof ExpenseUpdateSchema
     */
    estimatedAmount?: EstimatedAmount | null;
    /**
     *
     * @type {ActualAmount}
     * @memberof ExpenseUpdateSchema
     */
    actualAmount?: ActualAmount | null;
    /**
     *
     * @type {string}
     * @memberof ExpenseUpdateSchema
     */
    url?: string | null;
}

/**
 * Check if a given object implements the ExpenseUpdateSchema interface.
 */
export function instanceOfExpenseUpdateSchema(value: object): value is ExpenseUpdateSchema {
    return true;
}

export function ExpenseUpdateSchemaFromJSON(json: any): ExpenseUpdateSchema {
    return ExpenseUpdateSchemaFromJSONTyped(json, false);
}

export function ExpenseUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        item: json["item"] == null ? undefined : json["item"],
        description: json["description"] == null ? undefined : json["description"],
        date: json["date"] == null ? undefined : new Date(json["date"]),
        categoryId: json["category_id"] == null ? undefined : json["category_id"],
        vendorId: json["vendor_id"] == null ? undefined : json["vendor_id"],
        quantity: json["quantity"] == null ? undefined : json["quantity"],
        unitPrice: json["unit_price"] == null ? undefined : UnitPrice1FromJSON(json["unit_price"]),
        additionalPrice:
            json["additional_price"] == null ? undefined : AdditionalPrice1FromJSON(json["additional_price"]),
        estimatedAmount:
            json["estimated_amount"] == null ? undefined : EstimatedAmountFromJSON(json["estimated_amount"]),
        actualAmount: json["actual_amount"] == null ? undefined : ActualAmountFromJSON(json["actual_amount"]),
        url: json["url"] == null ? undefined : json["url"],
    };
}

export function ExpenseUpdateSchemaToJSON(json: any): ExpenseUpdateSchema {
    return ExpenseUpdateSchemaToJSONTyped(json, false);
}

export function ExpenseUpdateSchemaToJSONTyped(
    value?: ExpenseUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        item: value["item"],
        description: value["description"],
        date: value["date"] == null ? value["date"] : value["date"].toISOString().substring(0, 10),
        category_id: value["categoryId"],
        vendor_id: value["vendorId"],
        quantity: value["quantity"],
        unit_price: UnitPrice1ToJSON(value["unitPrice"]),
        additional_price: AdditionalPrice1ToJSON(value["additionalPrice"]),
        estimated_amount: EstimatedAmountToJSON(value["estimatedAmount"]),
        actual_amount: ActualAmountToJSON(value["actualAmount"]),
        url: value["url"],
    };
}
