/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuestGroupFilterSchema
 */
export interface GuestGroupFilterSchema {
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    relationship?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GuestGroupFilterSchema
     */
    priority?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GuestGroupFilterSchema
     */
    rsvpCode?: string | null;
}

/**
 * Check if a given object implements the GuestGroupFilterSchema interface.
 */
export function instanceOfGuestGroupFilterSchema(value: object): value is GuestGroupFilterSchema {
    return true;
}

export function GuestGroupFilterSchemaFromJSON(json: any): GuestGroupFilterSchema {
    return GuestGroupFilterSchemaFromJSONTyped(json, false);
}

export function GuestGroupFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestGroupFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'relationship': json['relationship'] == null ? undefined : json['relationship'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'rsvpCode': json['rsvp_code'] == null ? undefined : json['rsvp_code'],
    };
}

export function GuestGroupFilterSchemaToJSON(json: any): GuestGroupFilterSchema {
    return GuestGroupFilterSchemaToJSONTyped(json, false);
}

export function GuestGroupFilterSchemaToJSONTyped(value?: GuestGroupFilterSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'relationship': value['relationship'],
        'priority': value['priority'],
        'rsvp_code': value['rsvpCode'],
    };
}

