/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuestSchema
 */
export interface GuestSchema {
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    lastName: string;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    plusOne: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    groupId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    isInvited: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    isAttending: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    responded: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    acceptAccommodation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    acceptVip: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    accommodation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GuestSchema
     */
    vip: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuestSchema
     */
    notes: string;
    /**
     * 
     * @type {Date}
     * @memberof GuestSchema
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GuestSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the GuestSchema interface.
 */
export function instanceOfGuestSchema(value: object): value is GuestSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('plusOne' in value) || value['plusOne'] === undefined) return false;
    if (!('isInvited' in value) || value['isInvited'] === undefined) return false;
    if (!('isAttending' in value) || value['isAttending'] === undefined) return false;
    if (!('responded' in value) || value['responded'] === undefined) return false;
    if (!('acceptAccommodation' in value) || value['acceptAccommodation'] === undefined) return false;
    if (!('acceptVip' in value) || value['acceptVip'] === undefined) return false;
    if (!('accommodation' in value) || value['accommodation'] === undefined) return false;
    if (!('vip' in value) || value['vip'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GuestSchemaFromJSON(json: any): GuestSchema {
    return GuestSchemaFromJSONTyped(json, false);
}

export function GuestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'plusOne': json['plus_one'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'isInvited': json['is_invited'],
        'isAttending': json['is_attending'],
        'responded': json['responded'],
        'acceptAccommodation': json['accept_accommodation'],
        'acceptVip': json['accept_vip'],
        'accommodation': json['accommodation'],
        'vip': json['vip'],
        'notes': json['notes'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GuestSchemaToJSON(json: any): GuestSchema {
    return GuestSchemaToJSONTyped(json, false);
}

export function GuestSchemaToJSONTyped(value?: GuestSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'plus_one': value['plusOne'],
        'group_id': value['groupId'],
        'is_invited': value['isInvited'],
        'is_attending': value['isAttending'],
        'responded': value['responded'],
        'accept_accommodation': value['acceptAccommodation'],
        'accept_vip': value['acceptVip'],
        'accommodation': value['accommodation'],
        'vip': value['vip'],
        'notes': value['notes'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

