/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface IdeaSchema
 */
export interface IdeaSchema {
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    createdById?: string | null;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    createdByName?: string | null;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    updatedById?: string | null;
    /**
     *
     * @type {string}
     * @memberof IdeaSchema
     */
    updatedByName?: string | null;
    /**
     *
     * @type {Date}
     * @memberof IdeaSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof IdeaSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the IdeaSchema interface.
 */
export function instanceOfIdeaSchema(value: object): value is IdeaSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function IdeaSchemaFromJSON(json: any): IdeaSchema {
    return IdeaSchemaFromJSONTyped(json, false);
}

export function IdeaSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        createdById: json["created_by_id"] == null ? undefined : json["created_by_id"],
        createdByName: json["created_by_name"] == null ? undefined : json["created_by_name"],
        updatedById: json["updated_by_id"] == null ? undefined : json["updated_by_id"],
        updatedByName: json["updated_by_name"] == null ? undefined : json["updated_by_name"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function IdeaSchemaToJSON(json: any): IdeaSchema {
    return IdeaSchemaToJSONTyped(json, false);
}

export function IdeaSchemaToJSONTyped(value?: IdeaSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        created_by_id: value["createdById"],
        created_by_name: value["createdByName"],
        updated_by_id: value["updatedById"],
        updated_by_name: value["updatedByName"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
