/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface IdeaUpdateSchema
 */
export interface IdeaUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof IdeaUpdateSchema
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof IdeaUpdateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the IdeaUpdateSchema interface.
 */
export function instanceOfIdeaUpdateSchema(value: object): value is IdeaUpdateSchema {
    return true;
}

export function IdeaUpdateSchemaFromJSON(json: any): IdeaUpdateSchema {
    return IdeaUpdateSchemaFromJSONTyped(json, false);
}

export function IdeaUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function IdeaUpdateSchemaToJSON(json: any): IdeaUpdateSchema {
    return IdeaUpdateSchemaToJSONTyped(json, false);
}

export function IdeaUpdateSchemaToJSONTyped(
    value?: IdeaUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
    };
}
