/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface IdeaFilterSchema
 */
export interface IdeaFilterSchema {
    /**
     *
     * @type {string}
     * @memberof IdeaFilterSchema
     */
    name?: string | null;
}

/**
 * Check if a given object implements the IdeaFilterSchema interface.
 */
export function instanceOfIdeaFilterSchema(value: object): value is IdeaFilterSchema {
    return true;
}

export function IdeaFilterSchemaFromJSON(json: any): IdeaFilterSchema {
    return IdeaFilterSchemaFromJSONTyped(json, false);
}

export function IdeaFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function IdeaFilterSchemaToJSON(json: any): IdeaFilterSchema {
    return IdeaFilterSchemaToJSONTyped(json, false);
}

export function IdeaFilterSchemaToJSONTyped(
    value?: IdeaFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
