/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Input
 */
export interface Input {
    /**
     * 
     * @type {number}
     * @memberof Input
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof Input
     */
    pageSize?: number | null;
}

/**
 * Check if a given object implements the Input interface.
 */
export function instanceOfInput(value: object): value is Input {
    return true;
}

export function InputFromJSON(json: any): Input {
    return InputFromJSONTyped(json, false);
}

export function InputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Input {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
    };
}

export function InputToJSON(json: any): Input {
    return InputToJSONTyped(json, false);
}

export function InputToJSONTyped(value?: Input | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'page_size': value['pageSize'],
    };
}

