/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface InspirationFilterSchema
 */
export interface InspirationFilterSchema {
    /**
     *
     * @type {string}
     * @memberof InspirationFilterSchema
     */
    name?: string | null;
}

/**
 * Check if a given object implements the InspirationFilterSchema interface.
 */
export function instanceOfInspirationFilterSchema(value: object): value is InspirationFilterSchema {
    return true;
}

export function InspirationFilterSchemaFromJSON(json: any): InspirationFilterSchema {
    return InspirationFilterSchemaFromJSONTyped(json, false);
}

export function InspirationFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspirationFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function InspirationFilterSchemaToJSON(json: any): InspirationFilterSchema {
    return InspirationFilterSchemaToJSONTyped(json, false);
}

export function InspirationFilterSchemaToJSONTyped(
    value?: InspirationFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
