/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface InspirationSchema
 */
export interface InspirationSchema {
    /**
     *
     * @type {string}
     * @memberof InspirationSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof InspirationSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof InspirationSchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof InspirationSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof InspirationSchema
     */
    image?: string | null;
    /**
     *
     * @type {Date}
     * @memberof InspirationSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof InspirationSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the InspirationSchema interface.
 */
export function instanceOfInspirationSchema(value: object): value is InspirationSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function InspirationSchemaFromJSON(json: any): InspirationSchema {
    return InspirationSchemaFromJSONTyped(json, false);
}

export function InspirationSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspirationSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        image: json["image"] == null ? undefined : json["image"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function InspirationSchemaToJSON(json: any): InspirationSchema {
    return InspirationSchemaToJSONTyped(json, false);
}

export function InspirationSchemaToJSONTyped(
    value?: InspirationSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        image: value["image"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
