/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ListFilterSchema
 */
export interface ListFilterSchema {
    /**
     *
     * @type {string}
     * @memberof ListFilterSchema
     */
    name?: string | null;
}

/**
 * Check if a given object implements the ListFilterSchema interface.
 */
export function instanceOfListFilterSchema(value: object): value is ListFilterSchema {
    return true;
}

export function ListFilterSchemaFromJSON(json: any): ListFilterSchema {
    return ListFilterSchemaFromJSONTyped(json, false);
}

export function ListFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function ListFilterSchemaToJSON(json: any): ListFilterSchema {
    return ListFilterSchemaToJSONTyped(json, false);
}

export function ListFilterSchemaToJSONTyped(
    value?: ListFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
