/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { AdditionalPrice1 } from "./AdditionalPrice1";
import {
    AdditionalPrice1FromJSON,
    AdditionalPrice1FromJSONTyped,
    AdditionalPrice1ToJSON,
    AdditionalPrice1ToJSONTyped,
} from "./AdditionalPrice1";
import type { UnitPrice1 } from "./UnitPrice1";
import { UnitPrice1FromJSON, UnitPrice1FromJSONTyped, UnitPrice1ToJSON, UnitPrice1ToJSONTyped } from "./UnitPrice1";

/**
 *
 * @export
 * @interface ListEntryUpdateSchema
 */
export interface ListEntryUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    item?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    listId?: string | null;
    /**
     *
     * @type {number}
     * @memberof ListEntryUpdateSchema
     */
    order?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof ListEntryUpdateSchema
     */
    isCompleted?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof ListEntryUpdateSchema
     */
    purchased?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    vendorId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    associatedExpenseId?: string | null;
    /**
     *
     * @type {number}
     * @memberof ListEntryUpdateSchema
     */
    quantity?: number | null;
    /**
     *
     * @type {UnitPrice1}
     * @memberof ListEntryUpdateSchema
     */
    unitPrice?: UnitPrice1 | null;
    /**
     *
     * @type {AdditionalPrice1}
     * @memberof ListEntryUpdateSchema
     */
    additionalPrice?: AdditionalPrice1 | null;
    /**
     *
     * @type {string}
     * @memberof ListEntryUpdateSchema
     */
    url?: string | null;
}

/**
 * Check if a given object implements the ListEntryUpdateSchema interface.
 */
export function instanceOfListEntryUpdateSchema(value: object): value is ListEntryUpdateSchema {
    return true;
}

export function ListEntryUpdateSchemaFromJSON(json: any): ListEntryUpdateSchema {
    return ListEntryUpdateSchemaFromJSONTyped(json, false);
}

export function ListEntryUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEntryUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        item: json["item"] == null ? undefined : json["item"],
        description: json["description"] == null ? undefined : json["description"],
        listId: json["list_id"] == null ? undefined : json["list_id"],
        order: json["order"] == null ? undefined : json["order"],
        isCompleted: json["is_completed"] == null ? undefined : json["is_completed"],
        purchased: json["purchased"] == null ? undefined : json["purchased"],
        vendorId: json["vendor_id"] == null ? undefined : json["vendor_id"],
        associatedExpenseId: json["associated_expense_id"] == null ? undefined : json["associated_expense_id"],
        quantity: json["quantity"] == null ? undefined : json["quantity"],
        unitPrice: json["unit_price"] == null ? undefined : UnitPrice1FromJSON(json["unit_price"]),
        additionalPrice:
            json["additional_price"] == null ? undefined : AdditionalPrice1FromJSON(json["additional_price"]),
        url: json["url"] == null ? undefined : json["url"],
    };
}

export function ListEntryUpdateSchemaToJSON(json: any): ListEntryUpdateSchema {
    return ListEntryUpdateSchemaToJSONTyped(json, false);
}

export function ListEntryUpdateSchemaToJSONTyped(
    value?: ListEntryUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        item: value["item"],
        description: value["description"],
        list_id: value["listId"],
        order: value["order"],
        is_completed: value["isCompleted"],
        purchased: value["purchased"],
        vendor_id: value["vendorId"],
        associated_expense_id: value["associatedExpenseId"],
        quantity: value["quantity"],
        unit_price: UnitPrice1ToJSON(value["unitPrice"]),
        additional_price: AdditionalPrice1ToJSON(value["additionalPrice"]),
        url: value["url"],
    };
}
