/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ListSchema
 */
export interface ListSchema {
    /**
     *
     * @type {string}
     * @memberof ListSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ListSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ListSchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof ListSchema
     */
    description?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ListSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ListSchema
     */
    updatedAt: Date;
    /**
     *
     * @type {number}
     * @memberof ListSchema
     */
    totalEntries: number;
    /**
     *
     * @type {number}
     * @memberof ListSchema
     */
    completedEntries: number;
    /**
     *
     * @type {number}
     * @memberof ListSchema
     */
    pendingEntries: number;
    /**
     *
     * @type {number}
     * @memberof ListSchema
     */
    completionPercentage: number;
}

/**
 * Check if a given object implements the ListSchema interface.
 */
export function instanceOfListSchema(value: object): value is ListSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    if (!("totalEntries" in value) || value["totalEntries"] === undefined) return false;
    if (!("completedEntries" in value) || value["completedEntries"] === undefined) return false;
    if (!("pendingEntries" in value) || value["pendingEntries"] === undefined) return false;
    if (!("completionPercentage" in value) || value["completionPercentage"] === undefined) return false;
    return true;
}

export function ListSchemaFromJSON(json: any): ListSchema {
    return ListSchemaFromJSONTyped(json, false);
}

export function ListSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
        totalEntries: json["total_entries"],
        completedEntries: json["completed_entries"],
        pendingEntries: json["pending_entries"],
        completionPercentage: json["completion_percentage"],
    };
}

export function ListSchemaToJSON(json: any): ListSchema {
    return ListSchemaToJSONTyped(json, false);
}

export function ListSchemaToJSONTyped(value?: ListSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        slug: value["slug"],
        description: value["description"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
        total_entries: value["totalEntries"],
        completed_entries: value["completedEntries"],
        pending_entries: value["pendingEntries"],
        completion_percentage: value["completionPercentage"],
    };
}
