/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ListCreateSchema
 */
export interface ListCreateSchema {
    /**
     *
     * @type {string}
     * @memberof ListCreateSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ListCreateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ListCreateSchema interface.
 */
export function instanceOfListCreateSchema(value: object): value is ListCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function ListCreateSchemaFromJSON(json: any): ListCreateSchema {
    return ListCreateSchemaFromJSONTyped(json, false);
}

export function ListCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function ListCreateSchemaToJSON(json: any): ListCreateSchema {
    return ListCreateSchemaToJSONTyped(json, false);
}

export function ListCreateSchemaToJSONTyped(
    value?: ListCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        description: value["description"],
    };
}
