/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ListEntrySchema
 */
export interface ListEntrySchema {
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    item: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    slug: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    listId: string;
    /**
     *
     * @type {number}
     * @memberof ListEntrySchema
     */
    order: number;
    /**
     *
     * @type {boolean}
     * @memberof ListEntrySchema
     */
    isCompleted: boolean;
    /**
     *
     * @type {Date}
     * @memberof ListEntrySchema
     */
    completedAt?: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof ListEntrySchema
     */
    purchased: boolean;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    vendorId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    associatedExpenseId?: string | null;
    /**
     *
     * @type {number}
     * @memberof ListEntrySchema
     */
    quantity: number;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    unitPrice: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    additionalPrice: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    totalPrice: string;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    url?: string | null;
    /**
     *
     * @type {string}
     * @memberof ListEntrySchema
     */
    image?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ListEntrySchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ListEntrySchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ListEntrySchema interface.
 */
export function instanceOfListEntrySchema(value: object): value is ListEntrySchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("item" in value) || value["item"] === undefined) return false;
    if (!("slug" in value) || value["slug"] === undefined) return false;
    if (!("listId" in value) || value["listId"] === undefined) return false;
    if (!("order" in value) || value["order"] === undefined) return false;
    if (!("isCompleted" in value) || value["isCompleted"] === undefined) return false;
    if (!("purchased" in value) || value["purchased"] === undefined) return false;
    if (!("quantity" in value) || value["quantity"] === undefined) return false;
    if (!("unitPrice" in value) || value["unitPrice"] === undefined) return false;
    if (!("additionalPrice" in value) || value["additionalPrice"] === undefined) return false;
    if (!("totalPrice" in value) || value["totalPrice"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function ListEntrySchemaFromJSON(json: any): ListEntrySchema {
    return ListEntrySchemaFromJSONTyped(json, false);
}

export function ListEntrySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEntrySchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        item: json["item"],
        slug: json["slug"],
        description: json["description"] == null ? undefined : json["description"],
        listId: json["list_id"],
        order: json["order"],
        isCompleted: json["is_completed"],
        completedAt: json["completed_at"] == null ? undefined : new Date(json["completed_at"]),
        purchased: json["purchased"],
        vendorId: json["vendor_id"] == null ? undefined : json["vendor_id"],
        associatedExpenseId: json["associated_expense_id"] == null ? undefined : json["associated_expense_id"],
        quantity: json["quantity"],
        unitPrice: json["unit_price"],
        additionalPrice: json["additional_price"],
        totalPrice: json["total_price"],
        url: json["url"] == null ? undefined : json["url"],
        image: json["image"] == null ? undefined : json["image"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function ListEntrySchemaToJSON(json: any): ListEntrySchema {
    return ListEntrySchemaToJSONTyped(json, false);
}

export function ListEntrySchemaToJSONTyped(value?: ListEntrySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        item: value["item"],
        slug: value["slug"],
        description: value["description"],
        list_id: value["listId"],
        order: value["order"],
        is_completed: value["isCompleted"],
        completed_at:
            value["completedAt"] == null ? value["completedAt"] : value["completedAt"].toISOString().substring(0, 10),
        purchased: value["purchased"],
        vendor_id: value["vendorId"],
        associated_expense_id: value["associatedExpenseId"],
        quantity: value["quantity"],
        unit_price: value["unitPrice"],
        additional_price: value["additionalPrice"],
        total_price: value["totalPrice"],
        url: value["url"],
        image: value["image"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
