/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { AttachmentSchema } from "./AttachmentSchema";
import {
    AttachmentSchemaFromJSON,
    AttachmentSchemaFromJSONTyped,
    AttachmentSchemaToJSON,
    AttachmentSchemaToJSONTyped,
} from "./AttachmentSchema";

/**
 *
 * @export
 * @interface PagedAttachmentSchema
 */
export interface PagedAttachmentSchema {
    /**
     *
     * @type {Array<AttachmentSchema>}
     * @memberof PagedAttachmentSchema
     */
    items: Array<AttachmentSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedAttachmentSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedAttachmentSchema interface.
 */
export function instanceOfPagedAttachmentSchema(value: object): value is PagedAttachmentSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedAttachmentSchemaFromJSON(json: any): PagedAttachmentSchema {
    return PagedAttachmentSchemaFromJSONTyped(json, false);
}

export function PagedAttachmentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedAttachmentSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(AttachmentSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedAttachmentSchemaToJSON(json: any): PagedAttachmentSchema {
    return PagedAttachmentSchemaToJSONTyped(json, false);
}

export function PagedAttachmentSchemaToJSONTyped(
    value?: PagedAttachmentSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(AttachmentSchemaToJSON),
        count: value["count"],
    };
}
