/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ContactSchema } from "./ContactSchema";
import {
    ContactSchemaFromJSON,
    ContactSchemaFromJSONTyped,
    ContactSchemaToJSON,
    ContactSchemaToJSONTyped,
} from "./ContactSchema";

/**
 *
 * @export
 * @interface PagedContactSchema
 */
export interface PagedContactSchema {
    /**
     *
     * @type {Array<ContactSchema>}
     * @memberof PagedContactSchema
     */
    items: Array<ContactSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedContactSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedContactSchema interface.
 */
export function instanceOfPagedContactSchema(value: object): value is PagedContactSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedContactSchemaFromJSON(json: any): PagedContactSchema {
    return PagedContactSchemaFromJSONTyped(json, false);
}

export function PagedContactSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedContactSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(ContactSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedContactSchemaToJSON(json: any): PagedContactSchema {
    return PagedContactSchemaToJSONTyped(json, false);
}

export function PagedContactSchemaToJSONTyped(
    value?: PagedContactSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(ContactSchemaToJSON),
        count: value["count"],
    };
}
