/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { TimelineSchema } from "./TimelineSchema";
import {
    TimelineSchemaFromJSON,
    TimelineSchemaFromJSONTyped,
    TimelineSchemaToJSON,
    TimelineSchemaToJSONTyped,
} from "./TimelineSchema";

/**
 *
 * @export
 * @interface PagedTimelineSchema
 */
export interface PagedTimelineSchema {
    /**
     *
     * @type {Array<TimelineSchema>}
     * @memberof PagedTimelineSchema
     */
    items: Array<TimelineSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedTimelineSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedTimelineSchema interface.
 */
export function instanceOfPagedTimelineSchema(value: object): value is PagedTimelineSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedTimelineSchemaFromJSON(json: any): PagedTimelineSchema {
    return PagedTimelineSchemaFromJSONTyped(json, false);
}

export function PagedTimelineSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedTimelineSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(TimelineSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedTimelineSchemaToJSON(json: any): PagedTimelineSchema {
    return PagedTimelineSchemaToJSONTyped(json, false);
}

export function PagedTimelineSchemaToJSONTyped(
    value?: PagedTimelineSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(TimelineSchemaToJSON),
        count: value["count"],
    };
}
