/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ExpenseSchema } from "./ExpenseSchema";
import {
    ExpenseSchemaFromJSON,
    ExpenseSchemaFromJSONTyped,
    ExpenseSchemaToJSON,
    ExpenseSchemaToJSONTyped,
} from "./ExpenseSchema";

/**
 *
 * @export
 * @interface PagedExpenseSchema
 */
export interface PagedExpenseSchema {
    /**
     *
     * @type {Array<ExpenseSchema>}
     * @memberof PagedExpenseSchema
     */
    items: Array<ExpenseSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedExpenseSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedExpenseSchema interface.
 */
export function instanceOfPagedExpenseSchema(value: object): value is PagedExpenseSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedExpenseSchemaFromJSON(json: any): PagedExpenseSchema {
    return PagedExpenseSchemaFromJSONTyped(json, false);
}

export function PagedExpenseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedExpenseSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(ExpenseSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedExpenseSchemaToJSON(json: any): PagedExpenseSchema {
    return PagedExpenseSchemaToJSONTyped(json, false);
}

export function PagedExpenseSchemaToJSONTyped(
    value?: PagedExpenseSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(ExpenseSchemaToJSON),
        count: value["count"],
    };
}
