/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { AccommodationSchema } from "./AccommodationSchema";
import {
    AccommodationSchemaFromJSON,
    AccommodationSchemaFromJSONTyped,
    AccommodationSchemaToJSON,
    AccommodationSchemaToJSONTyped,
} from "./AccommodationSchema";

/**
 *
 * @export
 * @interface PagedAccommodationSchema
 */
export interface PagedAccommodationSchema {
    /**
     *
     * @type {Array<AccommodationSchema>}
     * @memberof PagedAccommodationSchema
     */
    items: Array<AccommodationSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedAccommodationSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedAccommodationSchema interface.
 */
export function instanceOfPagedAccommodationSchema(value: object): value is PagedAccommodationSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedAccommodationSchemaFromJSON(json: any): PagedAccommodationSchema {
    return PagedAccommodationSchemaFromJSONTyped(json, false);
}

export function PagedAccommodationSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PagedAccommodationSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(AccommodationSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedAccommodationSchemaToJSON(json: any): PagedAccommodationSchema {
    return PagedAccommodationSchemaToJSONTyped(json, false);
}

export function PagedAccommodationSchemaToJSONTyped(
    value?: PagedAccommodationSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(AccommodationSchemaToJSON),
        count: value["count"],
    };
}
