/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { InspirationSchema } from "./InspirationSchema";
import {
    InspirationSchemaFromJSON,
    InspirationSchemaFromJSONTyped,
    InspirationSchemaToJSON,
    InspirationSchemaToJSONTyped,
} from "./InspirationSchema";

/**
 *
 * @export
 * @interface PagedInspirationSchema
 */
export interface PagedInspirationSchema {
    /**
     *
     * @type {Array<InspirationSchema>}
     * @memberof PagedInspirationSchema
     */
    items: Array<InspirationSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedInspirationSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedInspirationSchema interface.
 */
export function instanceOfPagedInspirationSchema(value: object): value is PagedInspirationSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedInspirationSchemaFromJSON(json: any): PagedInspirationSchema {
    return PagedInspirationSchemaFromJSONTyped(json, false);
}

export function PagedInspirationSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedInspirationSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(InspirationSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedInspirationSchemaToJSON(json: any): PagedInspirationSchema {
    return PagedInspirationSchemaToJSONTyped(json, false);
}

export function PagedInspirationSchemaToJSONTyped(
    value?: PagedInspirationSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(InspirationSchemaToJSON),
        count: value["count"],
    };
}
