/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ListSchema } from "./ListSchema";
import { ListSchemaFromJSON, ListSchemaFromJSONTyped, ListSchemaToJSON, ListSchemaToJSONTyped } from "./ListSchema";

/**
 *
 * @export
 * @interface PagedListSchema
 */
export interface PagedListSchema {
    /**
     *
     * @type {Array<ListSchema>}
     * @memberof PagedListSchema
     */
    items: Array<ListSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedListSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedListSchema interface.
 */
export function instanceOfPagedListSchema(value: object): value is PagedListSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedListSchemaFromJSON(json: any): PagedListSchema {
    return PagedListSchemaFromJSONTyped(json, false);
}

export function PagedListSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedListSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(ListSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedListSchemaToJSON(json: any): PagedListSchema {
    return PagedListSchemaToJSONTyped(json, false);
}

export function PagedListSchemaToJSONTyped(value?: PagedListSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(ListSchemaToJSON),
        count: value["count"],
    };
}
