/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { RsvpSubmissionSchema } from "./RsvpSubmissionSchema";
import {
    RsvpSubmissionSchemaFromJSON,
    RsvpSubmissionSchemaFromJSONTyped,
    RsvpSubmissionSchemaToJSON,
    RsvpSubmissionSchemaToJSONTyped,
} from "./RsvpSubmissionSchema";

/**
 *
 * @export
 * @interface PagedRsvpSubmissionSchema
 */
export interface PagedRsvpSubmissionSchema {
    /**
     *
     * @type {Array<RsvpSubmissionSchema>}
     * @memberof PagedRsvpSubmissionSchema
     */
    items: Array<RsvpSubmissionSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedRsvpSubmissionSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedRsvpSubmissionSchema interface.
 */
export function instanceOfPagedRsvpSubmissionSchema(value: object): value is PagedRsvpSubmissionSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedRsvpSubmissionSchemaFromJSON(json: any): PagedRsvpSubmissionSchema {
    return PagedRsvpSubmissionSchemaFromJSONTyped(json, false);
}

export function PagedRsvpSubmissionSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PagedRsvpSubmissionSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(RsvpSubmissionSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedRsvpSubmissionSchemaToJSON(json: any): PagedRsvpSubmissionSchema {
    return PagedRsvpSubmissionSchemaToJSONTyped(json, false);
}

export function PagedRsvpSubmissionSchemaToJSONTyped(
    value?: PagedRsvpSubmissionSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(RsvpSubmissionSchemaToJSON),
        count: value["count"],
    };
}
