/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { DeadlineSchema } from "./DeadlineSchema";
import {
    DeadlineSchemaFromJSON,
    DeadlineSchemaFromJSONTyped,
    DeadlineSchemaToJSON,
    DeadlineSchemaToJSONTyped,
} from "./DeadlineSchema";

/**
 *
 * @export
 * @interface PagedDeadlineSchema
 */
export interface PagedDeadlineSchema {
    /**
     *
     * @type {Array<DeadlineSchema>}
     * @memberof PagedDeadlineSchema
     */
    items: Array<DeadlineSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedDeadlineSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedDeadlineSchema interface.
 */
export function instanceOfPagedDeadlineSchema(value: object): value is PagedDeadlineSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedDeadlineSchemaFromJSON(json: any): PagedDeadlineSchema {
    return PagedDeadlineSchemaFromJSONTyped(json, false);
}

export function PagedDeadlineSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedDeadlineSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(DeadlineSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedDeadlineSchemaToJSON(json: any): PagedDeadlineSchema {
    return PagedDeadlineSchemaToJSONTyped(json, false);
}

export function PagedDeadlineSchemaToJSONTyped(
    value?: PagedDeadlineSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(DeadlineSchemaToJSON),
        count: value["count"],
    };
}
