/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { DeadlineListSchema } from "./DeadlineListSchema";
import {
    DeadlineListSchemaFromJSON,
    DeadlineListSchemaFromJSONTyped,
    DeadlineListSchemaToJSON,
    DeadlineListSchemaToJSONTyped,
} from "./DeadlineListSchema";

/**
 *
 * @export
 * @interface PagedDeadlineListSchema
 */
export interface PagedDeadlineListSchema {
    /**
     *
     * @type {Array<DeadlineListSchema>}
     * @memberof PagedDeadlineListSchema
     */
    items: Array<DeadlineListSchema>;
    /**
     *
     * @type {number}
     * @memberof PagedDeadlineListSchema
     */
    count: number;
}

/**
 * Check if a given object implements the PagedDeadlineListSchema interface.
 */
export function instanceOfPagedDeadlineListSchema(value: object): value is PagedDeadlineListSchema {
    if (!("items" in value) || value["items"] === undefined) return false;
    if (!("count" in value) || value["count"] === undefined) return false;
    return true;
}

export function PagedDeadlineListSchemaFromJSON(json: any): PagedDeadlineListSchema {
    return PagedDeadlineListSchemaFromJSONTyped(json, false);
}

export function PagedDeadlineListSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedDeadlineListSchema {
    if (json == null) {
        return json;
    }
    return {
        items: (json["items"] as Array<any>).map(DeadlineListSchemaFromJSON),
        count: json["count"],
    };
}

export function PagedDeadlineListSchemaToJSON(json: any): PagedDeadlineListSchema {
    return PagedDeadlineListSchemaToJSONTyped(json, false);
}

export function PagedDeadlineListSchemaToJSONTyped(
    value?: PagedDeadlineListSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        items: (value["items"] as Array<any>).map(DeadlineListSchemaToJSON),
        count: value["count"],
    };
}
