/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface QRCodeTaskSchema
 */
export interface QRCodeTaskSchema {
    /**
     *
     * @type {boolean}
     * @memberof QRCodeTaskSchema
     */
    success: boolean;
    /**
     *
     * @type {string}
     * @memberof QRCodeTaskSchema
     */
    message: string;
    /**
     *
     * @type {string}
     * @memberof QRCodeTaskSchema
     */
    taskId: string;
}

/**
 * Check if a given object implements the QRCodeTaskSchema interface.
 */
export function instanceOfQRCodeTaskSchema(value: object): value is QRCodeTaskSchema {
    if (!("success" in value) || value["success"] === undefined) return false;
    if (!("message" in value) || value["message"] === undefined) return false;
    if (!("taskId" in value) || value["taskId"] === undefined) return false;
    return true;
}

export function QRCodeTaskSchemaFromJSON(json: any): QRCodeTaskSchema {
    return QRCodeTaskSchemaFromJSONTyped(json, false);
}

export function QRCodeTaskSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeTaskSchema {
    if (json == null) {
        return json;
    }
    return {
        success: json["success"],
        message: json["message"],
        taskId: json["task_id"],
    };
}

export function QRCodeTaskSchemaToJSON(json: any): QRCodeTaskSchema {
    return QRCodeTaskSchemaToJSONTyped(json, false);
}

export function QRCodeTaskSchemaToJSONTyped(
    value?: QRCodeTaskSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        success: value["success"],
        message: value["message"],
        task_id: value["taskId"],
    };
}
