/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface QuestionURLCreateSchema
 */
export interface QuestionURLCreateSchema {
    /**
     *
     * @type {string}
     * @memberof QuestionURLCreateSchema
     */
    questionId: string;
    /**
     *
     * @type {string}
     * @memberof QuestionURLCreateSchema
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof QuestionURLCreateSchema
     */
    text?: string | null;
}

/**
 * Check if a given object implements the QuestionURLCreateSchema interface.
 */
export function instanceOfQuestionURLCreateSchema(value: object): value is QuestionURLCreateSchema {
    if (!("questionId" in value) || value["questionId"] === undefined) return false;
    if (!("url" in value) || value["url"] === undefined) return false;
    return true;
}

export function QuestionURLCreateSchemaFromJSON(json: any): QuestionURLCreateSchema {
    return QuestionURLCreateSchemaFromJSONTyped(json, false);
}

export function QuestionURLCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionURLCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        questionId: json["question_id"],
        url: json["url"],
        text: json["text"] == null ? undefined : json["text"],
    };
}

export function QuestionURLCreateSchemaToJSON(json: any): QuestionURLCreateSchema {
    return QuestionURLCreateSchemaToJSONTyped(json, false);
}

export function QuestionURLCreateSchemaToJSONTyped(
    value?: QuestionURLCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        question_id: value["questionId"],
        url: value["url"],
        text: value["text"],
    };
}
