/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface QuestionURLSchema
 */
export interface QuestionURLSchema {
    /**
     *
     * @type {string}
     * @memberof QuestionURLSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof QuestionURLSchema
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof QuestionURLSchema
     */
    text?: string | null;
}

/**
 * Check if a given object implements the QuestionURLSchema interface.
 */
export function instanceOfQuestionURLSchema(value: object): value is QuestionURLSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("url" in value) || value["url"] === undefined) return false;
    return true;
}

export function QuestionURLSchemaFromJSON(json: any): QuestionURLSchema {
    return QuestionURLSchemaFromJSONTyped(json, false);
}

export function QuestionURLSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionURLSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        url: json["url"],
        text: json["text"] == null ? undefined : json["text"],
    };
}

export function QuestionURLSchemaToJSON(json: any): QuestionURLSchema {
    return QuestionURLSchemaToJSONTyped(json, false);
}

export function QuestionURLSchemaToJSONTyped(
    value?: QuestionURLSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        url: value["url"],
        text: value["text"],
    };
}
