/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface QuestionFilterSchema
 */
export interface QuestionFilterSchema {
    /**
     *
     * @type {string}
     * @memberof QuestionFilterSchema
     */
    category?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof QuestionFilterSchema
     */
    published?: boolean | null;
}

/**
 * Check if a given object implements the QuestionFilterSchema interface.
 */
export function instanceOfQuestionFilterSchema(value: object): value is QuestionFilterSchema {
    return true;
}

export function QuestionFilterSchemaFromJSON(json: any): QuestionFilterSchema {
    return QuestionFilterSchemaFromJSONTyped(json, false);
}

export function QuestionFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        category: json["category"] == null ? undefined : json["category"],
        published: json["published"] == null ? undefined : json["published"],
    };
}

export function QuestionFilterSchemaToJSON(json: any): QuestionFilterSchema {
    return QuestionFilterSchemaToJSONTyped(json, false);
}

export function QuestionFilterSchemaToJSONTyped(
    value?: QuestionFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        category: value["category"],
        published: value["published"],
    };
}
