/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ResponseChoiceSchema
 */
export interface ResponseChoiceSchema {
    /**
     *
     * @type {string}
     * @memberof ResponseChoiceSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ResponseChoiceSchema
     */
    text: string;
}

/**
 * Check if a given object implements the ResponseChoiceSchema interface.
 */
export function instanceOfResponseChoiceSchema(value: object): value is ResponseChoiceSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("text" in value) || value["text"] === undefined) return false;
    return true;
}

export function ResponseChoiceSchemaFromJSON(json: any): ResponseChoiceSchema {
    return ResponseChoiceSchemaFromJSONTyped(json, false);
}

export function ResponseChoiceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseChoiceSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        text: json["text"],
    };
}

export function ResponseChoiceSchemaToJSON(json: any): ResponseChoiceSchema {
    return ResponseChoiceSchemaToJSONTyped(json, false);
}

export function ResponseChoiceSchemaToJSONTyped(
    value?: ResponseChoiceSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        text: value["text"],
    };
}
