/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ResponseChoiceSchema } from "./ResponseChoiceSchema";
import {
    ResponseChoiceSchemaFromJSON,
    ResponseChoiceSchemaFromJSONTyped,
    ResponseChoiceSchemaToJSON,
    ResponseChoiceSchemaToJSONTyped,
} from "./ResponseChoiceSchema";

/**
 *
 * @export
 * @interface RsvpQuestionResponseSchema
 */
export interface RsvpQuestionResponseSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    id?: string | null;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    submissionId?: string | null;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    questionId: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    questionText: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    questionType: string;
    /**
     *
     * @type {number}
     * @memberof RsvpQuestionResponseSchema
     */
    questionOrder: number;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    responseText?: string | null;
    /**
     *
     * @type {Array<ResponseChoiceSchema>}
     * @memberof RsvpQuestionResponseSchema
     */
    responseChoices?: Array<ResponseChoiceSchema> | null;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionResponseSchema
     */
    createdAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionResponseSchema
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the RsvpQuestionResponseSchema interface.
 */
export function instanceOfRsvpQuestionResponseSchema(value: object): value is RsvpQuestionResponseSchema {
    if (!("questionId" in value) || value["questionId"] === undefined) return false;
    if (!("questionText" in value) || value["questionText"] === undefined) return false;
    if (!("questionType" in value) || value["questionType"] === undefined) return false;
    if (!("questionOrder" in value) || value["questionOrder"] === undefined) return false;
    return true;
}

export function RsvpQuestionResponseSchemaFromJSON(json: any): RsvpQuestionResponseSchema {
    return RsvpQuestionResponseSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionResponseSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpQuestionResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        submissionId: json["submission_id"] == null ? undefined : json["submission_id"],
        questionId: json["question_id"],
        questionText: json["question_text"],
        questionType: json["question_type"],
        questionOrder: json["question_order"],
        responseText: json["response_text"] == null ? undefined : json["response_text"],
        responseChoices:
            json["response_choices"] == null
                ? undefined
                : (json["response_choices"] as Array<any>).map(ResponseChoiceSchemaFromJSON),
        createdAt: json["created_at"] == null ? undefined : new Date(json["created_at"]),
        updatedAt: json["updated_at"] == null ? undefined : new Date(json["updated_at"]),
    };
}

export function RsvpQuestionResponseSchemaToJSON(json: any): RsvpQuestionResponseSchema {
    return RsvpQuestionResponseSchemaToJSONTyped(json, false);
}

export function RsvpQuestionResponseSchemaToJSONTyped(
    value?: RsvpQuestionResponseSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        submission_id: value["submissionId"],
        question_id: value["questionId"],
        question_text: value["questionText"],
        question_type: value["questionType"],
        question_order: value["questionOrder"],
        response_text: value["responseText"],
        response_choices:
            value["responseChoices"] == null
                ? undefined
                : (value["responseChoices"] as Array<any>).map(ResponseChoiceSchemaToJSON),
        created_at: value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
        updated_at: value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
    };
}
