/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface RsvpQuestionChoiceSchema
 */
export interface RsvpQuestionChoiceSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionChoiceSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionChoiceSchema
     */
    choiceText: string;
    /**
     *
     * @type {number}
     * @memberof RsvpQuestionChoiceSchema
     */
    order: number;
}

/**
 * Check if a given object implements the RsvpQuestionChoiceSchema interface.
 */
export function instanceOfRsvpQuestionChoiceSchema(value: object): value is RsvpQuestionChoiceSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("choiceText" in value) || value["choiceText"] === undefined) return false;
    if (!("order" in value) || value["order"] === undefined) return false;
    return true;
}

export function RsvpQuestionChoiceSchemaFromJSON(json: any): RsvpQuestionChoiceSchema {
    return RsvpQuestionChoiceSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionChoiceSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpQuestionChoiceSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        choiceText: json["choice_text"],
        order: json["order"],
    };
}

export function RsvpQuestionChoiceSchemaToJSON(json: any): RsvpQuestionChoiceSchema {
    return RsvpQuestionChoiceSchemaToJSONTyped(json, false);
}

export function RsvpQuestionChoiceSchemaToJSONTyped(
    value?: RsvpQuestionChoiceSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        choice_text: value["choiceText"],
        order: value["order"],
    };
}
