/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface RsvpSubmissionUpdateSchema
 */
export interface RsvpSubmissionUpdateSchema {
    /**
     *
     * @type {boolean}
     * @memberof RsvpSubmissionUpdateSchema
     */
    emailUpdates?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof RsvpSubmissionUpdateSchema
     */
    emailAddress?: string | null;
    /**
     *
     * @type {string}
     * @memberof RsvpSubmissionUpdateSchema
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the RsvpSubmissionUpdateSchema interface.
 */
export function instanceOfRsvpSubmissionUpdateSchema(value: object): value is RsvpSubmissionUpdateSchema {
    return true;
}

export function RsvpSubmissionUpdateSchemaFromJSON(json: any): RsvpSubmissionUpdateSchema {
    return RsvpSubmissionUpdateSchemaFromJSONTyped(json, false);
}

export function RsvpSubmissionUpdateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpSubmissionUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        emailUpdates: json["email_updates"] == null ? undefined : json["email_updates"],
        emailAddress: json["email_address"] == null ? undefined : json["email_address"],
        notes: json["notes"] == null ? undefined : json["notes"],
    };
}

export function RsvpSubmissionUpdateSchemaToJSON(json: any): RsvpSubmissionUpdateSchema {
    return RsvpSubmissionUpdateSchemaToJSONTyped(json, false);
}

export function RsvpSubmissionUpdateSchemaToJSONTyped(
    value?: RsvpSubmissionUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        email_updates: value["emailUpdates"],
        email_address: value["emailAddress"],
        notes: value["notes"],
    };
}
