/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface RsvpQuestionResponseSchema
 */
export interface RsvpQuestionResponseSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    submissionId: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    questionId: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionResponseSchema
     */
    responseText?: string | null;
    /**
     *
     * @type {Array<string>}
     * @memberof RsvpQuestionResponseSchema
     */
    responseChoiceIds: Array<string>;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionResponseSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionResponseSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the RsvpQuestionResponseSchema interface.
 */
export function instanceOfRsvpQuestionResponseSchema(value: object): value is RsvpQuestionResponseSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("submissionId" in value) || value["submissionId"] === undefined) return false;
    if (!("questionId" in value) || value["questionId"] === undefined) return false;
    if (!("responseChoiceIds" in value) || value["responseChoiceIds"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function RsvpQuestionResponseSchemaFromJSON(json: any): RsvpQuestionResponseSchema {
    return RsvpQuestionResponseSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionResponseSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpQuestionResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        submissionId: json["submission_id"],
        questionId: json["question_id"],
        responseText: json["response_text"] == null ? undefined : json["response_text"],
        responseChoiceIds: json["response_choice_ids"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function RsvpQuestionResponseSchemaToJSON(json: any): RsvpQuestionResponseSchema {
    return RsvpQuestionResponseSchemaToJSONTyped(json, false);
}

export function RsvpQuestionResponseSchemaToJSONTyped(
    value?: RsvpQuestionResponseSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        submission_id: value["submissionId"],
        question_id: value["questionId"],
        response_text: value["responseText"],
        response_choice_ids: value["responseChoiceIds"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
