/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface RsvpQuestionChoiceCreateSchema
 */
export interface RsvpQuestionChoiceCreateSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionChoiceCreateSchema
     */
    questionId: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionChoiceCreateSchema
     */
    choiceText: string;
    /**
     *
     * @type {number}
     * @memberof RsvpQuestionChoiceCreateSchema
     */
    order?: number | null;
}

/**
 * Check if a given object implements the RsvpQuestionChoiceCreateSchema interface.
 */
export function instanceOfRsvpQuestionChoiceCreateSchema(value: object): value is RsvpQuestionChoiceCreateSchema {
    if (!("questionId" in value) || value["questionId"] === undefined) return false;
    if (!("choiceText" in value) || value["choiceText"] === undefined) return false;
    return true;
}

export function RsvpQuestionChoiceCreateSchemaFromJSON(json: any): RsvpQuestionChoiceCreateSchema {
    return RsvpQuestionChoiceCreateSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionChoiceCreateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpQuestionChoiceCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        questionId: json["question_id"],
        choiceText: json["choice_text"],
        order: json["order"] == null ? undefined : json["order"],
    };
}

export function RsvpQuestionChoiceCreateSchemaToJSON(json: any): RsvpQuestionChoiceCreateSchema {
    return RsvpQuestionChoiceCreateSchemaToJSONTyped(json, false);
}

export function RsvpQuestionChoiceCreateSchemaToJSONTyped(
    value?: RsvpQuestionChoiceCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        question_id: value["questionId"],
        choice_text: value["choiceText"],
        order: value["order"],
    };
}
