/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface RsvpQuestionCreateSchema
 */
export interface RsvpQuestionCreateSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionCreateSchema
     */
    text: string;
    /**
     *
     * @type {number}
     * @memberof RsvpQuestionCreateSchema
     */
    order?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof RsvpQuestionCreateSchema
     */
    published?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionCreateSchema
     */
    questionType: string;
}

/**
 * Check if a given object implements the RsvpQuestionCreateSchema interface.
 */
export function instanceOfRsvpQuestionCreateSchema(value: object): value is RsvpQuestionCreateSchema {
    if (!("text" in value) || value["text"] === undefined) return false;
    if (!("questionType" in value) || value["questionType"] === undefined) return false;
    return true;
}

export function RsvpQuestionCreateSchemaFromJSON(json: any): RsvpQuestionCreateSchema {
    return RsvpQuestionCreateSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionCreateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RsvpQuestionCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        text: json["text"],
        order: json["order"] == null ? undefined : json["order"],
        published: json["published"] == null ? undefined : json["published"],
        questionType: json["question_type"],
    };
}

export function RsvpQuestionCreateSchemaToJSON(json: any): RsvpQuestionCreateSchema {
    return RsvpQuestionCreateSchemaToJSONTyped(json, false);
}

export function RsvpQuestionCreateSchemaToJSONTyped(
    value?: RsvpQuestionCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        text: value["text"],
        order: value["order"],
        published: value["published"],
        question_type: value["questionType"],
    };
}
