/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { RsvpQuestionChoiceSchema } from "./RsvpQuestionChoiceSchema";
import {
    RsvpQuestionChoiceSchemaFromJSON,
    RsvpQuestionChoiceSchemaFromJSONTyped,
    RsvpQuestionChoiceSchemaToJSON,
    RsvpQuestionChoiceSchemaToJSONTyped,
} from "./RsvpQuestionChoiceSchema";

/**
 *
 * @export
 * @interface RsvpQuestionSchema
 */
export interface RsvpQuestionSchema {
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionSchema
     */
    text: string;
    /**
     *
     * @type {number}
     * @memberof RsvpQuestionSchema
     */
    order: number;
    /**
     *
     * @type {boolean}
     * @memberof RsvpQuestionSchema
     */
    published: boolean;
    /**
     *
     * @type {string}
     * @memberof RsvpQuestionSchema
     */
    questionType: string;
    /**
     *
     * @type {Array<RsvpQuestionChoiceSchema>}
     * @memberof RsvpQuestionSchema
     */
    choices: Array<RsvpQuestionChoiceSchema>;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof RsvpQuestionSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the RsvpQuestionSchema interface.
 */
export function instanceOfRsvpQuestionSchema(value: object): value is RsvpQuestionSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("text" in value) || value["text"] === undefined) return false;
    if (!("order" in value) || value["order"] === undefined) return false;
    if (!("published" in value) || value["published"] === undefined) return false;
    if (!("questionType" in value) || value["questionType"] === undefined) return false;
    if (!("choices" in value) || value["choices"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function RsvpQuestionSchemaFromJSON(json: any): RsvpQuestionSchema {
    return RsvpQuestionSchemaFromJSONTyped(json, false);
}

export function RsvpQuestionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsvpQuestionSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        text: json["text"],
        order: json["order"],
        published: json["published"],
        questionType: json["question_type"],
        choices: (json["choices"] as Array<any>).map(RsvpQuestionChoiceSchemaFromJSON),
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function RsvpQuestionSchemaToJSON(json: any): RsvpQuestionSchema {
    return RsvpQuestionSchemaToJSONTyped(json, false);
}

export function RsvpQuestionSchemaToJSONTyped(
    value?: RsvpQuestionSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        text: value["text"],
        order: value["order"],
        published: value["published"],
        question_type: value["questionType"],
        choices: (value["choices"] as Array<any>).map(RsvpQuestionChoiceSchemaToJSON),
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
