/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RsvpSubmissionSchema
 */
export interface RsvpSubmissionSchema {
    /**
     * 
     * @type {string}
     * @memberof RsvpSubmissionSchema
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RsvpSubmissionSchema
     */
    guestGroupId: string;
    /**
     * 
     * @type {boolean}
     * @memberof RsvpSubmissionSchema
     */
    emailUpdates: boolean;
    /**
     * 
     * @type {string}
     * @memberof RsvpSubmissionSchema
     */
    emailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof RsvpSubmissionSchema
     */
    notes: string;
    /**
     * 
     * @type {number}
     * @memberof RsvpSubmissionSchema
     */
    acceptAccommodationCount: number;
    /**
     * 
     * @type {number}
     * @memberof RsvpSubmissionSchema
     */
    acceptVipCount: number;
    /**
     * 
     * @type {Date}
     * @memberof RsvpSubmissionSchema
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RsvpSubmissionSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the RsvpSubmissionSchema interface.
 */
export function instanceOfRsvpSubmissionSchema(value: object): value is RsvpSubmissionSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('guestGroupId' in value) || value['guestGroupId'] === undefined) return false;
    if (!('emailUpdates' in value) || value['emailUpdates'] === undefined) return false;
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('acceptAccommodationCount' in value) || value['acceptAccommodationCount'] === undefined) return false;
    if (!('acceptVipCount' in value) || value['acceptVipCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RsvpSubmissionSchemaFromJSON(json: any): RsvpSubmissionSchema {
    return RsvpSubmissionSchemaFromJSONTyped(json, false);
}

export function RsvpSubmissionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RsvpSubmissionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'guestGroupId': json['guest_group_id'],
        'emailUpdates': json['email_updates'],
        'emailAddress': json['email_address'],
        'notes': json['notes'],
        'acceptAccommodationCount': json['accept_accommodation_count'],
        'acceptVipCount': json['accept_vip_count'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function RsvpSubmissionSchemaToJSON(json: any): RsvpSubmissionSchema {
    return RsvpSubmissionSchemaToJSONTyped(json, false);
}

export function RsvpSubmissionSchemaToJSONTyped(value?: RsvpSubmissionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'guest_group_id': value['guestGroupId'],
        'email_updates': value['emailUpdates'],
        'email_address': value['emailAddress'],
        'notes': value['notes'],
        'accept_accommodation_count': value['acceptAccommodationCount'],
        'accept_vip_count': value['acceptVipCount'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

