/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TimelineCreateSchema
 */
export interface TimelineCreateSchema {
    /**
     *
     * @type {string}
     * @memberof TimelineCreateSchema
     */
    name: string;
    /**
     *
     * @type {Date}
     * @memberof TimelineCreateSchema
     */
    start: Date;
    /**
     *
     * @type {Date}
     * @memberof TimelineCreateSchema
     */
    end?: Date | null;
    /**
     *
     * @type {number}
     * @memberof TimelineCreateSchema
     */
    order?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof TimelineCreateSchema
     */
    published?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof TimelineCreateSchema
     */
    confirmed?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof TimelineCreateSchema
     */
    description?: string | null;
}

/**
 * Check if a given object implements the TimelineCreateSchema interface.
 */
export function instanceOfTimelineCreateSchema(value: object): value is TimelineCreateSchema {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("start" in value) || value["start"] === undefined) return false;
    return true;
}

export function TimelineCreateSchemaFromJSON(json: any): TimelineCreateSchema {
    return TimelineCreateSchemaFromJSONTyped(json, false);
}

export function TimelineCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        start: new Date(json["start"]),
        end: json["end"] == null ? undefined : new Date(json["end"]),
        order: json["order"] == null ? undefined : json["order"],
        published: json["published"] == null ? undefined : json["published"],
        confirmed: json["confirmed"] == null ? undefined : json["confirmed"],
        description: json["description"] == null ? undefined : json["description"],
    };
}

export function TimelineCreateSchemaToJSON(json: any): TimelineCreateSchema {
    return TimelineCreateSchemaToJSONTyped(json, false);
}

export function TimelineCreateSchemaToJSONTyped(
    value?: TimelineCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        start: value["start"].toISOString(),
        end: value["end"] == null ? value["end"] : value["end"].toISOString(),
        order: value["order"],
        published: value["published"],
        confirmed: value["confirmed"],
        description: value["description"],
    };
}
