/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TimelineFilterSchema
 */
export interface TimelineFilterSchema {
    /**
     *
     * @type {string}
     * @memberof TimelineFilterSchema
     */
    name?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof TimelineFilterSchema
     */
    published?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof TimelineFilterSchema
     */
    confirmed?: boolean | null;
}

/**
 * Check if a given object implements the TimelineFilterSchema interface.
 */
export function instanceOfTimelineFilterSchema(value: object): value is TimelineFilterSchema {
    return true;
}

export function TimelineFilterSchemaFromJSON(json: any): TimelineFilterSchema {
    return TimelineFilterSchemaFromJSONTyped(json, false);
}

export function TimelineFilterSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineFilterSchema {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        published: json["published"] == null ? undefined : json["published"],
        confirmed: json["confirmed"] == null ? undefined : json["confirmed"],
    };
}

export function TimelineFilterSchemaToJSON(json: any): TimelineFilterSchema {
    return TimelineFilterSchemaToJSONTyped(json, false);
}

export function TimelineFilterSchemaToJSONTyped(
    value?: TimelineFilterSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        published: value["published"],
        confirmed: value["confirmed"],
    };
}
