/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TipsCreateSchema
 */
export interface TipsCreateSchema {
    /**
     *
     * @type {string}
     * @memberof TipsCreateSchema
     */
    categoryId: string;
    /**
     *
     * @type {string}
     * @memberof TipsCreateSchema
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof TipsCreateSchema
     */
    order?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof TipsCreateSchema
     */
    published?: boolean | null;
}

/**
 * Check if a given object implements the TipsCreateSchema interface.
 */
export function instanceOfTipsCreateSchema(value: object): value is TipsCreateSchema {
    if (!("categoryId" in value) || value["categoryId"] === undefined) return false;
    if (!("content" in value) || value["content"] === undefined) return false;
    return true;
}

export function TipsCreateSchemaFromJSON(json: any): TipsCreateSchema {
    return TipsCreateSchemaFromJSONTyped(json, false);
}

export function TipsCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TipsCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        categoryId: json["category_id"],
        content: json["content"],
        order: json["order"] == null ? undefined : json["order"],
        published: json["published"] == null ? undefined : json["published"],
    };
}

export function TipsCreateSchemaToJSON(json: any): TipsCreateSchema {
    return TipsCreateSchemaToJSONTyped(json, false);
}

export function TipsCreateSchemaToJSONTyped(
    value?: TipsCreateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        category_id: value["categoryId"],
        content: value["content"],
        order: value["order"],
        published: value["published"],
    };
}
