/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TipsUpdateSchema
 */
export interface TipsUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof TipsUpdateSchema
     */
    categoryId?: string | null;
    /**
     *
     * @type {string}
     * @memberof TipsUpdateSchema
     */
    content?: string | null;
    /**
     *
     * @type {number}
     * @memberof TipsUpdateSchema
     */
    order?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof TipsUpdateSchema
     */
    published?: boolean | null;
}

/**
 * Check if a given object implements the TipsUpdateSchema interface.
 */
export function instanceOfTipsUpdateSchema(value: object): value is TipsUpdateSchema {
    return true;
}

export function TipsUpdateSchemaFromJSON(json: any): TipsUpdateSchema {
    return TipsUpdateSchemaFromJSONTyped(json, false);
}

export function TipsUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TipsUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        categoryId: json["category_id"] == null ? undefined : json["category_id"],
        content: json["content"] == null ? undefined : json["content"],
        order: json["order"] == null ? undefined : json["order"],
        published: json["published"] == null ? undefined : json["published"],
    };
}

export function TipsUpdateSchemaToJSON(json: any): TipsUpdateSchema {
    return TipsUpdateSchemaToJSONTyped(json, false);
}

export function TipsUpdateSchemaToJSONTyped(
    value?: TipsUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        category_id: value["categoryId"],
        content: value["content"],
        order: value["order"],
        published: value["published"],
    };
}
