/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TipsSchema
 */
export interface TipsSchema {
    /**
     *
     * @type {string}
     * @memberof TipsSchema
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof TipsSchema
     */
    category: string;
    /**
     *
     * @type {string}
     * @memberof TipsSchema
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof TipsSchema
     */
    order: number;
    /**
     *
     * @type {boolean}
     * @memberof TipsSchema
     */
    published: boolean;
    /**
     *
     * @type {Date}
     * @memberof TipsSchema
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof TipsSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TipsSchema interface.
 */
export function instanceOfTipsSchema(value: object): value is TipsSchema {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("category" in value) || value["category"] === undefined) return false;
    if (!("content" in value) || value["content"] === undefined) return false;
    if (!("order" in value) || value["order"] === undefined) return false;
    if (!("published" in value) || value["published"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    return true;
}

export function TipsSchemaFromJSON(json: any): TipsSchema {
    return TipsSchemaFromJSONTyped(json, false);
}

export function TipsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TipsSchema {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        category: json["category"],
        content: json["content"],
        order: json["order"],
        published: json["published"],
        createdAt: new Date(json["created_at"]),
        updatedAt: new Date(json["updated_at"]),
    };
}

export function TipsSchemaToJSON(json: any): TipsSchema {
    return TipsSchemaToJSONTyped(json, false);
}

export function TipsSchemaToJSONTyped(value?: TipsSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        category: value["category"],
        content: value["content"],
        order: value["order"],
        published: value["published"],
        created_at: value["createdAt"].toISOString(),
        updated_at: value["updatedAt"].toISOString(),
    };
}
