/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface WeddingSettingsSchema
 */
export interface WeddingSettingsSchema {
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    defaultDataLoaded: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    allowRsvp: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    allowPhotos: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    showFaq: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    showVenue: boolean;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsSchema
     */
    weddingDate?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsSchema
     */
    rsvpStartDate?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsSchema
     */
    rsvpEndDate?: Date | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAcceptButton: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpDeclineButton: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAttendingLabel: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAccommodationLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpVipLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAcceptIntro: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAcceptSuccessMessage: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpDeclineSuccessMessage: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpAccommodationIntro?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpVipIntro: string;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    rsvpShowAccommodationIntro: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    rsvpShowVipIntro: boolean;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsSchema
     */
    rsvpEnableEmailUpdates: boolean;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpEmailUpdateLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    rsvpSuccessHeadline: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    standardGroupLabel: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    vipGroupLabel: string;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsSchema
     */
    accommodationGroupLabel: string;
}

/**
 * Check if a given object implements the WeddingSettingsSchema interface.
 */
export function instanceOfWeddingSettingsSchema(value: object): value is WeddingSettingsSchema {
    if (!("defaultDataLoaded" in value) || value["defaultDataLoaded"] === undefined) return false;
    if (!("allowRsvp" in value) || value["allowRsvp"] === undefined) return false;
    if (!("allowPhotos" in value) || value["allowPhotos"] === undefined) return false;
    if (!("showFaq" in value) || value["showFaq"] === undefined) return false;
    if (!("showVenue" in value) || value["showVenue"] === undefined) return false;
    if (!("rsvpAcceptButton" in value) || value["rsvpAcceptButton"] === undefined) return false;
    if (!("rsvpDeclineButton" in value) || value["rsvpDeclineButton"] === undefined) return false;
    if (!("rsvpAttendingLabel" in value) || value["rsvpAttendingLabel"] === undefined) return false;
    if (!("rsvpAcceptIntro" in value) || value["rsvpAcceptIntro"] === undefined) return false;
    if (!("rsvpAcceptSuccessMessage" in value) || value["rsvpAcceptSuccessMessage"] === undefined) return false;
    if (!("rsvpDeclineSuccessMessage" in value) || value["rsvpDeclineSuccessMessage"] === undefined) return false;
    if (!("rsvpVipIntro" in value) || value["rsvpVipIntro"] === undefined) return false;
    if (!("rsvpShowAccommodationIntro" in value) || value["rsvpShowAccommodationIntro"] === undefined) return false;
    if (!("rsvpShowVipIntro" in value) || value["rsvpShowVipIntro"] === undefined) return false;
    if (!("rsvpEnableEmailUpdates" in value) || value["rsvpEnableEmailUpdates"] === undefined) return false;
    if (!("rsvpSuccessHeadline" in value) || value["rsvpSuccessHeadline"] === undefined) return false;
    if (!("standardGroupLabel" in value) || value["standardGroupLabel"] === undefined) return false;
    if (!("vipGroupLabel" in value) || value["vipGroupLabel"] === undefined) return false;
    if (!("accommodationGroupLabel" in value) || value["accommodationGroupLabel"] === undefined) return false;
    return true;
}

export function WeddingSettingsSchemaFromJSON(json: any): WeddingSettingsSchema {
    return WeddingSettingsSchemaFromJSONTyped(json, false);
}

export function WeddingSettingsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeddingSettingsSchema {
    if (json == null) {
        return json;
    }
    return {
        defaultDataLoaded: json["default_data_loaded"],
        allowRsvp: json["allow_rsvp"],
        allowPhotos: json["allow_photos"],
        showFaq: json["show_faq"],
        showVenue: json["show_venue"],
        weddingDate: json["wedding_date"] == null ? undefined : new Date(json["wedding_date"]),
        rsvpStartDate: json["rsvp_start_date"] == null ? undefined : new Date(json["rsvp_start_date"]),
        rsvpEndDate: json["rsvp_end_date"] == null ? undefined : new Date(json["rsvp_end_date"]),
        rsvpAcceptButton: json["rsvp_accept_button"],
        rsvpDeclineButton: json["rsvp_decline_button"],
        rsvpAttendingLabel: json["rsvp_attending_label"],
        rsvpAccommodationLabel: json["rsvp_accommodation_label"] == null ? undefined : json["rsvp_accommodation_label"],
        rsvpVipLabel: json["rsvp_vip_label"] == null ? undefined : json["rsvp_vip_label"],
        rsvpAcceptIntro: json["rsvp_accept_intro"],
        rsvpAcceptSuccessMessage: json["rsvp_accept_success_message"],
        rsvpDeclineSuccessMessage: json["rsvp_decline_success_message"],
        rsvpAccommodationIntro: json["rsvp_accommodation_intro"] == null ? undefined : json["rsvp_accommodation_intro"],
        rsvpVipIntro: json["rsvp_vip_intro"],
        rsvpShowAccommodationIntro: json["rsvp_show_accommodation_intro"],
        rsvpShowVipIntro: json["rsvp_show_vip_intro"],
        rsvpEnableEmailUpdates: json["rsvp_enable_email_updates"],
        rsvpEmailUpdateLabel: json["rsvp_email_update_label"] == null ? undefined : json["rsvp_email_update_label"],
        rsvpSuccessHeadline: json["rsvp_success_headline"],
        standardGroupLabel: json["standard_group_label"],
        vipGroupLabel: json["vip_group_label"],
        accommodationGroupLabel: json["accommodation_group_label"],
    };
}

export function WeddingSettingsSchemaToJSON(json: any): WeddingSettingsSchema {
    return WeddingSettingsSchemaToJSONTyped(json, false);
}

export function WeddingSettingsSchemaToJSONTyped(
    value?: WeddingSettingsSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        default_data_loaded: value["defaultDataLoaded"],
        allow_rsvp: value["allowRsvp"],
        allow_photos: value["allowPhotos"],
        show_faq: value["showFaq"],
        show_venue: value["showVenue"],
        wedding_date:
            value["weddingDate"] == null ? value["weddingDate"] : value["weddingDate"].toISOString().substring(0, 10),
        rsvp_start_date:
            value["rsvpStartDate"] == null
                ? value["rsvpStartDate"]
                : value["rsvpStartDate"].toISOString().substring(0, 10),
        rsvp_end_date:
            value["rsvpEndDate"] == null ? value["rsvpEndDate"] : value["rsvpEndDate"].toISOString().substring(0, 10),
        rsvp_accept_button: value["rsvpAcceptButton"],
        rsvp_decline_button: value["rsvpDeclineButton"],
        rsvp_attending_label: value["rsvpAttendingLabel"],
        rsvp_accommodation_label: value["rsvpAccommodationLabel"],
        rsvp_vip_label: value["rsvpVipLabel"],
        rsvp_accept_intro: value["rsvpAcceptIntro"],
        rsvp_accept_success_message: value["rsvpAcceptSuccessMessage"],
        rsvp_decline_success_message: value["rsvpDeclineSuccessMessage"],
        rsvp_accommodation_intro: value["rsvpAccommodationIntro"],
        rsvp_vip_intro: value["rsvpVipIntro"],
        rsvp_show_accommodation_intro: value["rsvpShowAccommodationIntro"],
        rsvp_show_vip_intro: value["rsvpShowVipIntro"],
        rsvp_enable_email_updates: value["rsvpEnableEmailUpdates"],
        rsvp_email_update_label: value["rsvpEmailUpdateLabel"],
        rsvp_success_headline: value["rsvpSuccessHeadline"],
        standard_group_label: value["standardGroupLabel"],
        vip_group_label: value["vipGroupLabel"],
        accommodation_group_label: value["accommodationGroupLabel"],
    };
}
