/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface WeddingSettingsUpdateSchema
 */
export interface WeddingSettingsUpdateSchema {
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    defaultDataLoaded?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    allowRsvp?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    allowPhotos?: boolean | null;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsUpdateSchema
     */
    weddingDate?: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    showFaq?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    showVenue?: boolean | null;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpStartDate?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpEndDate?: Date | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAcceptButton?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpDeclineButton?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAttendingLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAccommodationLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpVipLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAcceptIntro?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAcceptSuccessMessage?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpDeclineSuccessMessage?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpAccommodationIntro?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpVipIntro?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpShowAccommodationIntro?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpShowVipIntro?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpEnableEmailUpdates?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpEmailUpdateLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    rsvpSuccessHeadline?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    standardGroupLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    vipGroupLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    accommodationGroupLabel?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venuePageTitle?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venuePageDescription?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueName?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueAddressLineOne?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueAddressLineTwo?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueCity?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueState?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueZipcode?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueCountry?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueParking?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueGalleryTitle?: string | null;
    /**
     *
     * @type {string}
     * @memberof WeddingSettingsUpdateSchema
     */
    venueGalleryDescription?: string | null;
}

/**
 * Check if a given object implements the WeddingSettingsUpdateSchema interface.
 */
export function instanceOfWeddingSettingsUpdateSchema(value: object): value is WeddingSettingsUpdateSchema {
    return true;
}

export function WeddingSettingsUpdateSchemaFromJSON(json: any): WeddingSettingsUpdateSchema {
    return WeddingSettingsUpdateSchemaFromJSONTyped(json, false);
}

export function WeddingSettingsUpdateSchemaFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): WeddingSettingsUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        defaultDataLoaded: json["default_data_loaded"] == null ? undefined : json["default_data_loaded"],
        allowRsvp: json["allow_rsvp"] == null ? undefined : json["allow_rsvp"],
        allowPhotos: json["allow_photos"] == null ? undefined : json["allow_photos"],
        weddingDate: json["wedding_date"] == null ? undefined : new Date(json["wedding_date"]),
        showFaq: json["show_faq"] == null ? undefined : json["show_faq"],
        showVenue: json["show_venue"] == null ? undefined : json["show_venue"],
        rsvpStartDate: json["rsvp_start_date"] == null ? undefined : new Date(json["rsvp_start_date"]),
        rsvpEndDate: json["rsvp_end_date"] == null ? undefined : new Date(json["rsvp_end_date"]),
        rsvpAcceptButton: json["rsvp_accept_button"] == null ? undefined : json["rsvp_accept_button"],
        rsvpDeclineButton: json["rsvp_decline_button"] == null ? undefined : json["rsvp_decline_button"],
        rsvpAttendingLabel: json["rsvp_attending_label"] == null ? undefined : json["rsvp_attending_label"],
        rsvpAccommodationLabel: json["rsvp_accommodation_label"] == null ? undefined : json["rsvp_accommodation_label"],
        rsvpVipLabel: json["rsvp_vip_label"] == null ? undefined : json["rsvp_vip_label"],
        rsvpAcceptIntro: json["rsvp_accept_intro"] == null ? undefined : json["rsvp_accept_intro"],
        rsvpAcceptSuccessMessage:
            json["rsvp_accept_success_message"] == null ? undefined : json["rsvp_accept_success_message"],
        rsvpDeclineSuccessMessage:
            json["rsvp_decline_success_message"] == null ? undefined : json["rsvp_decline_success_message"],
        rsvpAccommodationIntro: json["rsvp_accommodation_intro"] == null ? undefined : json["rsvp_accommodation_intro"],
        rsvpVipIntro: json["rsvp_vip_intro"] == null ? undefined : json["rsvp_vip_intro"],
        rsvpShowAccommodationIntro:
            json["rsvp_show_accommodation_intro"] == null ? undefined : json["rsvp_show_accommodation_intro"],
        rsvpShowVipIntro: json["rsvp_show_vip_intro"] == null ? undefined : json["rsvp_show_vip_intro"],
        rsvpEnableEmailUpdates:
            json["rsvp_enable_email_updates"] == null ? undefined : json["rsvp_enable_email_updates"],
        rsvpEmailUpdateLabel: json["rsvp_email_update_label"] == null ? undefined : json["rsvp_email_update_label"],
        rsvpSuccessHeadline: json["rsvp_success_headline"] == null ? undefined : json["rsvp_success_headline"],
        standardGroupLabel: json["standard_group_label"] == null ? undefined : json["standard_group_label"],
        vipGroupLabel: json["vip_group_label"] == null ? undefined : json["vip_group_label"],
        accommodationGroupLabel:
            json["accommodation_group_label"] == null ? undefined : json["accommodation_group_label"],
        venuePageTitle: json["venue_page_title"] == null ? undefined : json["venue_page_title"],
        venuePageDescription: json["venue_page_description"] == null ? undefined : json["venue_page_description"],
        venueName: json["venue_name"] == null ? undefined : json["venue_name"],
        venueAddressLineOne: json["venue_address_line_one"] == null ? undefined : json["venue_address_line_one"],
        venueAddressLineTwo: json["venue_address_line_two"] == null ? undefined : json["venue_address_line_two"],
        venueCity: json["venue_city"] == null ? undefined : json["venue_city"],
        venueState: json["venue_state"] == null ? undefined : json["venue_state"],
        venueZipcode: json["venue_zipcode"] == null ? undefined : json["venue_zipcode"],
        venueCountry: json["venue_country"] == null ? undefined : json["venue_country"],
        venueParking: json["venue_parking"] == null ? undefined : json["venue_parking"],
        venueGalleryTitle: json["venue_gallery_title"] == null ? undefined : json["venue_gallery_title"],
        venueGalleryDescription:
            json["venue_gallery_description"] == null ? undefined : json["venue_gallery_description"],
    };
}

export function WeddingSettingsUpdateSchemaToJSON(json: any): WeddingSettingsUpdateSchema {
    return WeddingSettingsUpdateSchemaToJSONTyped(json, false);
}

export function WeddingSettingsUpdateSchemaToJSONTyped(
    value?: WeddingSettingsUpdateSchema | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        default_data_loaded: value["defaultDataLoaded"],
        allow_rsvp: value["allowRsvp"],
        allow_photos: value["allowPhotos"],
        wedding_date:
            value["weddingDate"] == null ? value["weddingDate"] : value["weddingDate"].toISOString().substring(0, 10),
        show_faq: value["showFaq"],
        show_venue: value["showVenue"],
        rsvp_start_date:
            value["rsvpStartDate"] == null
                ? value["rsvpStartDate"]
                : value["rsvpStartDate"].toISOString().substring(0, 10),
        rsvp_end_date:
            value["rsvpEndDate"] == null ? value["rsvpEndDate"] : value["rsvpEndDate"].toISOString().substring(0, 10),
        rsvp_accept_button: value["rsvpAcceptButton"],
        rsvp_decline_button: value["rsvpDeclineButton"],
        rsvp_attending_label: value["rsvpAttendingLabel"],
        rsvp_accommodation_label: value["rsvpAccommodationLabel"],
        rsvp_vip_label: value["rsvpVipLabel"],
        rsvp_accept_intro: value["rsvpAcceptIntro"],
        rsvp_accept_success_message: value["rsvpAcceptSuccessMessage"],
        rsvp_decline_success_message: value["rsvpDeclineSuccessMessage"],
        rsvp_accommodation_intro: value["rsvpAccommodationIntro"],
        rsvp_vip_intro: value["rsvpVipIntro"],
        rsvp_show_accommodation_intro: value["rsvpShowAccommodationIntro"],
        rsvp_show_vip_intro: value["rsvpShowVipIntro"],
        rsvp_enable_email_updates: value["rsvpEnableEmailUpdates"],
        rsvp_email_update_label: value["rsvpEmailUpdateLabel"],
        rsvp_success_headline: value["rsvpSuccessHeadline"],
        standard_group_label: value["standardGroupLabel"],
        vip_group_label: value["vipGroupLabel"],
        accommodation_group_label: value["accommodationGroupLabel"],
        venue_page_title: value["venuePageTitle"],
        venue_page_description: value["venuePageDescription"],
        venue_name: value["venueName"],
        venue_address_line_one: value["venueAddressLineOne"],
        venue_address_line_two: value["venueAddressLineTwo"],
        venue_city: value["venueCity"],
        venue_state: value["venueState"],
        venue_zipcode: value["venueZipcode"],
        venue_country: value["venueCountry"],
        venue_parking: value["venueParking"],
        venue_gallery_title: value["venueGalleryTitle"],
        venue_gallery_description: value["venueGalleryDescription"],
    };
}
